### ISSUE TITLE
PWA shows sometimes a white screen

### ISSUE THREAD

**Issue by samydoesit** [GoogleChrome/workbox#2982] opened 2021-11-19 19:11 UTC
**Library Affected**:
"workbox-cacheable-response": "^6.4.1",
"workbox-core": "^6.4.1",
"workbox-expiration": "^6.4.1",
"workbox-google-analytics": "^6.4.1",
"workbox-precaching": "^6.4.1",
"workbox-routing": "^6.4.1",
"workbox-strategies": "^6.4.1",
"workbox-window": "^6.4.1",
"workbox-webpack-plugin": "^6.4.1",

**Browser & Platform**:
Chrome 96.0.4664.55 on MacOS 12.0.1 Monterey

**Issue or Feature Request Description**:
I am not exactly sure if i am right here and how to explain it best, but we are experiencing some strange PWA behaviour.
If we open certain url's sometimes our PWA renders a blank screen while the dom is fully loaded like normal, no errors everything looks fine. Devtools is showing the dom like there is no problem, we can even hover over elements (that are in this state invisible to us) and click them and the pwa does it's stuff reloads but it keeps rendering a white screen.

When we used workbox version 6.3.0 it didn't stopped rendering the white screen when we accessed these certain urls even after reopening the pwa.  As i today updated to workbox 6.4.1 this behaviour changed a bit so when the pwa renders a white screen and we now close it and open it again it is now working for some reason. 

It's still rendering a white screen on the first load but after closing and reopening it is now working. 🤷‍♂️

This Bug tends to only appear on MacOS desktop using Chrome.

Maybe thats more of an issue of pwa's with chromium but because it has changed a bit after updating workbox i thought to ask here first.

This Chromium issue is looking to be related 
[https://bugs.chromium.org/p/chromium/issues/detail?id=1239155&q=blank%20screen%20pwa&can=2](https://bugs.chromium.org/p/chromium/issues/detail?id=1239155&q=blank%20screen%20pwa&can=2)

The problem is that there is no visible problem log or anything to us. It's not happening if we just use the browser.

I can sometimes see the same thing on twitter's pwa.
[Screencast of the bug from Twitters PWA](https://drive.google.com/file/d/1iqVOByIo4nMh23yF9A8Rm4Eho-7tAcXZ/view?usp=sharing)

Maybe someone can point me to the right direction.

**Comment by HappyDustbunny** [comment] 2021-12-21 09:31
My vanilla javascript pwa also shows a white screen sometimes, but on Chrome for Android (fully updated on a Samsung S8).

I can't reproduce the bug consistently, but it seems to appear after the app loses focus sometimes. Like when I turn off the screen of my phone for a while. I don't _**think**_ the length of time is critical, and neither is losing connection a factor, but I may be wrong here as it happens every other day at random times and I have a hard time remembering what I did prior to the white screen.

Closing the pwa and restarting it removes the problem.

Everything is fine in Chrome dev-tools when I look with chrome://inspect/#devices except for the screen being white.
It registers swipes (which I logged for debugging and forgot to remove), but the buttons is inactive even though the full DOM appears to be there.

As I don't see this problem on the PC I don't think this is down to my code. Especially when no errors is thrown and Lighthouse gives a clean bill.

(The code for my pwa can be found at https://github.com/HappyDustbunny/FuzzyPlan and it is hosted at fuzzyplan.madshorn.dk )

Edit: I saw a suggestion somewhere else that the white screen could be a lingering theme_color or background_color, but after changing them both to different colors the white screen persist occasionally.

**Comment by HappyDustbunny** [comment] 2022-01-11 13:41
My vanilla javascript pwa also shows a white screen sometimes, but on Chrome for Android (fully updated on a Samsung S8).

I can't reproduce the bug consistently, but it seems to appear after the app loses focus sometimes. Like when I turn off the screen of my phone for a while. I don't _**think**_ the length of time is critical, and neither is losing connection a factor, but I may be wrong here as it happens every other day at random times and I have a hard time remembering what I did prior to the white screen.

Closing the pwa and restarting it removes the problem.

Everything is fine in Chrome dev-tools when I look with chrome://inspect/#devices except for the screen being white.
It registers swipes (which I logged for debugging and forgot to remove), but the buttons is inactive even though the full DOM appears to be there.

As I don't see this problem on the PC I don't think this is down to my code. Especially when no errors is thrown and Lighthouse gives a clean bill.

(The code for my pwa can be found at https://github.com/HappyDustbunny/FuzzyPlan and it is hosted at fuzzyplan.madshorn.dk )

Edit: I saw a suggestion somewhere else that the white screen could be a lingering theme_color or background_color, but after changing them both to different colors the white screen persist occasionally.

**Comment by nouman-te** [comment] 2022-01-26 11:08
In my React PWA, i also see the blank screen.
**Library**
workbox 6.4.2
**Platform**
Chrome Version 97.0.4692.99 MacOS Monterey Version 12.1
When i open install PWA for first time it does show content. When i switch to dark theme, it show me a blank screen. 
I'm not sure if someone is facing the same issue in dark mode or not.

**Comment by tomayac** [comment] 2024-04-25 08:46
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team

**Closed as completed by tomayac** 2024-04-25 08:46 UTC
