### ISSUE TITLE
website does not work offline

### ISSUE THREAD

**Issue by samccone** [GoogleChrome/workbox#552] opened 2017-05-16 15:59 UTC
![image](https://cloud.githubusercontent.com/assets/883126/26115827/ff533346-3a15-11e7-8365-748dbbbf5b12.png)

**Comment by jeffposnick** [comment] 2017-05-17 17:40
Hey @samccone—I'm not able to reproduce with the current deployment. We've been iterating quite a bit on the site, and it's possible that you hit us at a time when not everything was set up properly.

If you can reproduce now, can you re-open (and maybe grab one of us to let us debug the repro in person?)

<img width="1557" alt="screen shot 2017-05-17 at 10 36 24 am" src="https://cloud.githubusercontent.com/assets/1749548/26167926/2d86ba62-3aed-11e7-898b-556b06333ff3.png">

**Comment by samccone** [comment] 2017-05-17 20:25
will do

**Comment by gauntface** [comment] 2017-05-17 21:45
You got this because you were offline and our service worker was borked.

Should be fixed soon.

**Comment by jeffposnick** [comment] 2017-05-18 17:20
I believe @gauntface adjusted the build to make sure this doesn't crop up again.

**Closed by jeffposnick** 2017-05-18 17:20 UTC
Labels: P1
