### ISSUE TITLE
workbox-webpack-plugin doesn't work with webpack --watch

### ISSUE THREAD

**Issue by EtienneT** [GoogleChrome/workbox#2404] opened 2020-03-13 14:02 UTC
**Library Affected**:
workbox-webpack-plugin

**Issue or Feature Request Description**:
When using webpack with the --watch command argument, it rebuilds scripts automatically when you change files.  But it doesn't work for rebuilding the generated SW file when the swSrc file changes.

**Comment by jeffposnick** [comment] 2020-03-13 15:53
My understanding is that the following code is supposed to handle that:

https://github.com/GoogleChrome/workbox/blob/a284beedb84f7e5d36694fce60bb4267000b1d5a/packages/workbox-webpack-plugin/src/inject-manifest.js#L237-L239

@prateekbh, in your `webpack` plugin experience, have you run into anything similar?

**Comment by EtienneT** [comment] 2020-03-13 18:07
I see something happen in the console window running webpack when I save the file in swSrc, I see the Date modified change on disk for swDest but my latest changes are not there.  Nothing changes on disk.  I have to close webpack and run it again.

**Comment by prateekbh** [comment] 2020-03-13 19:20
hmm i am unable to reproduce this as my changes are reflected as expected in the file.

@EtienneT what kinda changes are you making? Are they in the pre-cache manifest or your actual code?

**Comment by EtienneT** [comment] 2020-03-13 19:29
Here is my configuration in webpack:

new workboxPlugin.InjectManifest({
                swSrc: 'js/ServiceWorker/sw.js',
                swDest: 'sw-generated.js',
                chunks: ['Common', 'Vendor', 'Dashboard'],
                additionalManifestEntries: swFiles,
                exclude: [/.*bundle.js.map.*/, /.*\.eot.*/, /.*\.svg.*/, /.*\.ttf.*/]
            })

If I modify js/ServiceWorker/sw.js, webpack won't really update sw-generated.js.  The write date is changed, but the browser never pick up any changes.  If I look in the file and search for strings I just added, it is not there.  For example just to test I added var blah = 2;, then search for blah in the file and could not find it even though Notepad++ said it updated.

**Comment by n1kk** [comment] 2020-05-28 15:23
Similar issue. Hot reload doesn't work in dev server either. I see webpack in the console updating when I edit my `swSrc` file, but if I navigate in browser to `/sw.js` it still old code, I need to restart webpack to force changes to appear.
in my webpack config
```js
new InjectManifest({
    swSrc: "./src/services/cache-service/cache.worker.ts",
    swDest: "sw.js"
})
```
My service worker is in typescript but I've tried plain js file and it's the same issue.

**Comment by jeffposnick** [comment] 2020-05-29 15:52
I'm really having a hard time reproducing this.

Here's a screencast of me running through the steps you're describing, but things work as expected (the `console.log()` message included in the `build/sw.js` file updates when I change it in `src/sw.js`).

https://drive.google.com/file/d/1BuiJLqTKZd5zdljshgDa2Bne82xvO3pV/view?usp=sharing

It's using this really basic set of files: https://gist.github.com/jeffposnick/c366abb09c375224ff4ed2acb767f838

If you're seeing an issue, do you notice anything different about your setup vs. what I'm demoing? Are you able to reproduce the issue if you follow the steps I did?

**Comment by jeffposnick** [comment] 2021-04-23 19:21
Given that I'm unable to reproduce, and have shared a working configuration, and that we've released new updates to `workbox-webpack-plugin` since the original report, I'm going to close this issue.

If you're still running into this issue with the current version of `workbox-webpack-plugin`, sharing a configuration that can reproduce the issue would be appreciated, and we can reopen at that point.

**Closed by jeffposnick** 2021-04-23 19:21 UTC
Labels: Bug, workbox-webpack-plugin

**Comment by AlexSirenko** [comment] 2021-07-09 09:20
Have the same problem, but it works if run webpack for bundling sw separately.
