### ISSUE TITLE
Precaching issue for Android Chrome v50-v56

### ISSUE THREAD

**Issue by ishangulati** [GoogleChrome/workbox#1769] opened 2018-11-28 10:08 UTC
<img width="858" alt="useragent_chromeversion51" src="https://user-images.githubusercontent.com/21355920/49142870-c5a10500-f31f-11e8-8b7b-264d2742e094.png">

**Library Affected**:
workbox-precaching
<img width="751" alt="source_code" src="https://user-images.githubusercontent.com/21355920/49144522-99878300-f323-11e8-9626-3c5c927657be.png">

**Browser & Platform**:
Android Google Chrome v50 - v56 (might be in other older versions as well)

**Issue or Feature Request Description**:
Uglified code for precaching module causing error due to precedence of yield operator over ternary in above specified Android Google Chrome versions.
<img width="1122" alt="uglified_prod_code" src="https://user-images.githubusercontent.com/21355920/49143553-46accc00-f321-11e8-8dc3-a92b5032962f.png">

Suggested solution could be to rewrite "CleanRedirect" function so that it's minified to something like below.
<img width="1121" alt="fixed_prod_code" src="https://user-images.githubusercontent.com/21355920/49143573-4f9d9d80-f321-11e8-8244-6b4a343614c7.png">

**Comment by ishangulati** [comment] 2018-11-28 15:37
Hey @jeffposnick we are facing this issue on a number of devices running v50-56 as captured by our logs. For replicating this we used an actual Android device running Chrome v51 (refer useragent in first screenshot) and accessed it via USB debugging.
This seems like a case when yield is not uglified as expected to target older versions.

**Comment by jeffposnick** [comment] 2018-11-28 19:43
I [downloaded a build](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/430246/) of Chromium v56.0.2913.0 for the Mac to try this out.

I visited a random website that happens to use `workbox-precaching` v3.6.1, https://m.nascar.com/galleries/#/0

Things loaded properly, without any errors:

<img width="674" alt="screen shot 2018-11-28 at 2 41 37 pm" src="https://user-images.githubusercontent.com/1749548/49177665-cd5eaa80-f31b-11e8-8b96-00e5ef6c21f8.png">

Do you have a URL that you could share that demonstrates the failure to evaluate the bundled `workbox-precaching` script?

**Comment by ishangulati** [comment] 2018-11-29 08:55
We faced similar issue on https://m.nascar.com/galleries/#/0 while accessing it on our device.
<img width="1440" alt="nascar_sw_error" src="https://user-images.githubusercontent.com/21355920/49209676-1f1d3880-f3e1-11e8-8b85-4eaf69480ea7.png">

Please use https://buyerfront-msitepreprod.stg.snapdeal.com/sw.js to access our service worker. Also we attaching a list of useragents who are encountering similar issue while accessing our website.
[data.csv.zip](https://github.com/GoogleChrome/workbox/files/2628289/data.csv.zip)

**Comment by ishangulati** [comment] 2019-05-15 18:11
Any update on this?

**Comment by jeffposnick** [comment] 2019-05-16 14:45
Hello @ishangulati—Apologies for the lack of update. 

I've consistently been unable to reproduce this issue when using older versions of Chrome locally to test it out.

I'll also note that the Workbox v3 branch is no longer active, and in [Workbox v4](https://github.com/GoogleChrome/workbox/releases/tag/v4.0.0), the pre-bundled libraries are transpiled based on the capabilities of Chrome 56 or higher.

One of the things you can do with Workbox v4, is to create your own custom bundle of the Workbox runtime libraries, via webpack or Rollup, following [this guide](https://developers.google.com/web/tools/workbox/guides/using-bundlers). As part of this bundling process you can add in a transpilation step using [`@babel/preset-env`](https://babeljs.io/docs/en/babel-preset-env) that outputs code which meets whatever requirements you have.

Given that the Workbox v3 branch is no longer active, and that there's a clearer path forward in Workbox v4 to create your own bundles, I'm going to close this issue.

**Closed by jeffposnick** 2019-05-16 14:45 UTC
Labels: Browser Compatibility, Bug, workbox-precaching
