### ISSUE TITLE
Error: Invalid schema object - webpack

### ISSUE THREAD

**Issue by williammanco** [GoogleChrome/workbox#2456] opened 2020-04-15 08:12 UTC
Hi everyone, when I compile my application with webpack get an error on console.
The problem is on this file _**workbox-build > build > options > partials > generate.js**_
in this lines of code: 
`.when('navigationPreload', {
    is: true,
    then: joi.required()
  }),`

if remove this not have error in console.

**Library Affected**:
workbox-build

**Browser & Platform**:
all browsers

**Console Error**
`Error: Invalid schema object
    at new module.exports (mypath/node_modules/@hapi/hoek/lib/error.js:23:19)
    at Object.module.exports [as assert] (mypath/node_modules/@hapi/hoek/lib/assert.js:20:11)
    at internals.Array.concat (mypath/node_modules/@hapi/joi/lib/types/any/index.js:143:14)
    at internals.Array.when (mypath/node_modules/@hapi/joi/lib/types/any/index.js:436:60)
    at Object.<anonymous> (mypath/node_modules/workbox-build/build/options/partials/generate.js:62:45)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (mypath/node_modules/workbox-build/build/options/schema/webpack-generate-sw.js:16:25)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (mypath/node_modules/workbox-webpack-plugin/build/generate-sw.js:20:33)
    at Module._compile (internal/modules/cjs/loader.js:688:30)`

**Comment by jeffposnick** [comment] 2020-04-15 17:48
Could you provide your full `GenerateSW()` configuration, along with the version of `workbox-webpack-plugin` and `webpack` that you're using?

I just gave it a quick try, and the relevant parameter validation does appear to be working as expected.

This line is meant to check that when `navigationPreload` is set, `runtimeCaching` also needs to be set:

https://github.com/GoogleChrome/workbox/blob/26958c6ce3fa3bb394117e2aead51c92b08d6a4a/packages/workbox-build/src/options/partials/generate.js#L78-L81

**Comment by williammanco** [comment] 2020-04-16 09:42
Hi @jeffposnick,

this is my GenerateSW configuration (the last on plugins list in webpack configuration)
```  
new GenerateSW({
          swDest: 'sw.js',
          clientsClaim: true,
          skipWaiting: true,
          navigationPreload: false,
          offlineGoogleAnalytics: true,
        }),
```

and the version of modules:
`"workbox-webpack-plugin": "^5.1.2"`
`"webpack": "^4.25.1"`

Thanks

**Comment by jeffposnick** [comment] 2020-04-16 15:06
I'm not able to reproduce this.

I started from scratch with the following `webpack.config.js`:

```
const path = require('path');
const {GenerateSW} = require('workbox-webpack-plugin');

module.exports = {
  entry: path.join(__dirname, 'src', 'app.js'),
  mode: 'development',
  output: {
    path: path.join(__dirname, 'build'),
  },
  plugins: [
    new GenerateSW({
      swDest: 'sw.js',
      clientsClaim: true,
      skipWaiting: true,
      navigationPreload: false,
      offlineGoogleAnalytics: true,
    }),
  ],
};
```

`src/app.js` is something really basic, like `console.log('hello')`.

I'm able to successfully run the `webpack` build and a service worker file is generated.

Can you start fresh—remove your `node_modules` and reinstall everything, or do this in a new directory—and see if you can reproduce the issue still?

**Comment by williammanco** [comment] 2020-04-21 10:22
Hello @jeffposnick!

Ok after many attempts with a fresh installation, the problem seems the package "webpack-merge", but it's very strange because if I change order of import, GenerateSW don't show errors.

from (show error)
```
const merge = require('webpack-merge');
const { GenerateSW } = require('workbox-webpack-plugin');
```
to (work correctly)
```
const { GenerateSW } = require('workbox-webpack-plugin');
const merge = require('webpack-merge');
```

**Comment by jeffposnick** [comment] 2020-04-21 13:41
Okay, thanks for debugging this further.

I don't know that there's anything actionable that we can do on the Workbox side of things to prevent this behavior—it sounds more like `webpack-merge` is doing something that messes with the underlying `joi` validation library dependency.

I'm going to close this for now unless there's something that comes up which we could be doing differently.

**Closed by jeffposnick** 2020-04-21 13:41 UTC
Labels: Bug, Needs More Info, workbox-build
