### ISSUE TITLE
workbox background sync - callback

### ISSUE THREAD

**Issue by GlauberF** [GoogleChrome/workbox#1632] opened 2018-09-14 18:42 UTC
I'm in love with the workbox library, super delighted.

Now I'm working with **workbox background sync**, using for methods http (**PUT, DELETE, UPDATE**).

My question, when the user tries to perform a delete without internet, by default will return an error, as I can get / verify if there is this error if it was stored for later when the internet back perform ** background sync **.

Briefly, I need to know if that request was successfully stored, later to be executed with background sync.

**Comment by jeffposnick** [comment] 2018-09-14 18:58
There are a [number of callbacks](https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.backgroundSync.Queue#Queue) that you can pass in when configuring the `Queue` (passing them in to the `Plugin` constructor will forward them on to the `Queue` constructor). I'm not totally clear on what you're trying to accomplish, but the callbacks are worth investigating:

```javascript
const plugin = new workbox.backgroundSync.Plugin('my-queue-name', {
  callbacks: {
    requestWillEnqueue: (storableRequest) => {
      // ...
    },
    requestWillReplay: (storableRequest) => {
      // ...
    },
    queueDidReplay: (storableRequestArray) => {
      // ...
    },
  },
});
```

Does that help?

**Comment by GlauberF** [comment] 2018-09-14 19:34
but these actions do not issue some event, that I could recover in any part of the system?

**Comment by jeffposnick** [comment] 2018-09-21 15:57
Pretty sure that this is a duplicate of https://github.com/GoogleChrome/workbox/issues/1637

**Closed by jeffposnick** 2018-09-21 15:57 UTC
Labels: Needs More Info, workbox-background-sync
