### ISSUE TITLE
If you use the `swSrc` option `workbox-sw.prod.v1.0.1.js` is not copied into the output directory.

### ISSUE THREAD

**Issue by cgreening** [GoogleChrome/workbox#672] opened 2017-07-11 13:54 UTC
**Library Affected**:
workbox webpack plugin

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
If you use the `swSrc` option `workbox-sw.prod.v1.0.1.js` is not copied into the output directory.

```js
    new workboxPlugin({
      globDirectory: 'build',
      globPatterns: ['*.*'],
      swDest: path.join('build', 'sw.js'),
    })
```
Results in two files being added to the build directory `sw.js` and `workbox-sw.prod.v1.0.1.js`

```js
    new workboxPlugin({
      globDirectory: 'build',
      globPatterns: ['*.*'],
      swDest: path.join('build', 'sw.js'),
      swSrc: 'src/sw.js'
    })
```

Results in only `sw.js` in the build directory. Application fails at runtime as it cannot find `workbox-sw.prod.v1.0.1.js`

I think the correct behaviour should be to always copy `workbox-sw.prod.v1.0.1.js`?

**Comment by cgreening** [comment] 2017-07-11 14:15
Looks like there is already a pull request for this: https://github.com/GoogleChrome/workbox/pull/654

**Comment by gauntface** [comment] 2017-07-14 18:08
Duplicate of #650

**Closed by gauntface** 2017-07-14 18:08 UTC
