### ISSUE TITLE
Not working with webpack-dev-server

### ISSUE THREAD

**Issue by rubenspgcavalcante** [GoogleChrome/workbox#1256] opened 2018-01-30 14:34 UTC
**Library Affected**:
*workbox-build*

**My environment**
Node v8.6.0
- webpack: v3.10.0,
- webpack-dev-server: v2.9.7
- workbox-webpack-plugin: v2.1.2

**Issue or Feature Request Description**:
Even with the #808 the workbox still waiting for the files be in the filesystem to map them inside the sw.
With the sample configuration:
```js
    new WorkboxWebpackPlugin({
      globDirectory: './dist',
      globPatterns: ['**/*.{html,js}'],
      swDest: path.join('./dist', 'sw.js'),
      clientsClaim: true,
      skipWaiting: true
    })
```

If I run it with webpack-dev-server (all files are set in memory and not written on the file system) the plugin will just fail 😞 
```
Error: One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": "./dist",
  "globPattern": "**/*.{html,js}",
  "globIgnores": [
    "node_modules/**/*",
    "workbox-sw.prod.v2.1.2.js",
    "sw.js"
  ]
}
```

But if I run the webpack build before (the files will be written inside `dist/`) and then run the webpack-dev-server, it will run just fine 👌 .

So, even if the sw is caching stuff served by the dev-server, it still needing to map the bundle, chunk and file names coming from the **filesystem**

**Comment by gauntface** [comment] 2018-01-30 17:24
Thanks for the bug - we have actually improved this a lot in V3 which should be hitting Beta soon (next week or so), so I'm going to close this issue for now - you can find more info here: https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin

duplicate of: https://github.com/GoogleChrome/workbox/issues/577

**Closed by gauntface** 2018-01-30 17:24 UTC
