### ISSUE TITLE
Service worker skipWaiting not activating workbox service worker

### ISSUE THREAD

**Issue by kanishk-anand-oyo** [GoogleChrome/workbox#1995] opened 2019-04-01 12:08 UTC
**Library Affected**:
*workbox-sw.*

**Browser & Platform**:
*All*

**Issue or Feature Request Description**:
*I have migrated from SW-Precache to workbox service worker, and during the process, I've updated service worker filename from 'service-worker.js' to 'service-worker-mobile.js' and also added `workbox.skipWaiting()` in the new service worker file, implying that as soon as new service worker file is downloaded, and installed, it should get activated, but, I can still see my old service worker file running. Any help here? *

**Comment by philipwalton** [comment] 2019-04-01 17:35
What does the [service worker registration](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration) object report? E.g. the result of `await navigator.serviceWorker.getRegistration()`.

It's possible for `skipWaiting()` to not cause your existing service worker to be replaced if it's still waiting for an event promise to settle. This can happen if you pass `event.waitUntil()` a promise that never resolves.

**Comment by CaptainCodeman** [comment] 2019-04-19 00:26
I see the same thing. Service worker doesn't update even though skipWaiting is called, no other tabs open, no waitUntil.

**Comment by jeffposnick** [comment] 2019-07-24 16:04
Renaming your `service-worker.js` to something else, like `service-worker-mobile.js` is likely the cause of the problem. Your previously cached `index.html`, which includes a call to register `service-worker.js`, is likely be executed, and will be indefinitely.

The recommended approach is to keep a consistent service worker name. This is described in more detail at https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#avoid-url-change

**Closed by jeffposnick** 2019-07-24 16:04 UTC

**Comment by valgussev** [comment] 2020-04-01 10:03
I have quite similar problem.

According to https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/skipWaiting skipWaiting should return a promise which should be **immediately** resolved but for some reason the promise never resolves.

In order to showcase that I need to:
1. Switch context to installed service worker from devtools console dropdown
2. Call `skipWaiting` and expect the promise to be resolved
```
self.skipWaiting().then(args => console.log('installed', args))
```
3. Nothing is printed in the console meaning that the promise is never resolved
4. If in devtools Application -> Service Worker send a `skipWaiting` message by clicking Push the promise will be resolved printing out `installed, undefined`

My service worker file is called `service-worker.js` and it never been renamed. Also I'm not using any custom `waitUntil` and it seems imported workbox version does not either https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-sw.js

**Comment by valgussev** [comment] 2020-04-06 04:57
It turned out that introducing in-flight requests after calling skipWaiting causes them (on Chrome specifically) to not to be properly resolved making waiting sw to not to be able to activate before the [timeout](https://github.com/chromium/chromium/blob/b33bdc0d74538fb44d7797f5d3d94cce9242d079/content/browser/service_worker/service_worker_registration.cc#L419) is triggered.

**Comment by jketcham** [comment] 2020-05-01 17:19
@valgussev I've been experiencing essentially the same problem you outlined.

Did you come up with a solution to consistently not have `skipWaiting` interfere with in-flight requests?

I wanted to allow users to initiate the skipWaiting process on the waiting service worker, but I got inconsistencies where sometimes skipWaiting would work and other times it would never leave the waiting stage. I tried adding an exponential backoff on calling skipWaiting to try and avoid interfering with in-flight requests, but that didn't work.

I ended up having to go the skipWaiting-on-install route and reload the clients when a new controller is detected. Less ideal but it was the most consistent in my testing.

**Comment by valgussev** [comment] 2020-05-04 05:45
Unfortunately we were not able to dig fully enough into the issue in order to understand the root causes, what we ended up doing is moving all the network related logic before posting skipWaiting trigger message to service worker.

**Comment by jketcham** [comment] 2020-05-04 21:10
Gotcha, thanks for the info!

**Comment by viniciuskneves** [comment] 2020-07-03 06:36
> @valgussev I've been experiencing essentially the same problem you outlined.
> 
> Did you come up with a solution to consistently not have `skipWaiting` interfere with in-flight requests?
> 
> I wanted to allow users to initiate the skipWaiting process on the waiting service worker, but I got inconsistencies where sometimes skipWaiting would work and other times it would never leave the waiting stage. I tried adding an exponential backoff on calling skipWaiting to try and avoid interfering with in-flight requests, but that didn't work.
> 
> I ended up having to go the skipWaiting-on-install route and reload the clients when a new controller is detected. Less ideal but it was the most consistent in my testing.

I'm currently doing the same but it refreshes the page out of the blue after a while sometimes.

@valgussev any clues if using Workbox v5 could help here? I'm currently using v4 and I don't know if v5 would somehow help (I don't see how to be honest but it doesn't hurt to ask 😅)

**Comment by valgussev** [comment] 2020-07-03 07:45
sorry, I don't have experiences with the latest workbox version. The refresh you are referencing can also be due to a timeout mentioned above.

**Comment by viniciuskneves** [comment] 2020-07-03 07:51
> sorry, I don't have experiences with the latest workbox version. The refresh you are referencing can also be due to a timeout mentioned above.

Yep, that is what I'm thinking =[

**Comment by cilliemalan** [comment] 2020-12-03 10:32
> I see the same thing. Service worker doesn't update even though skipWaiting is called, no other tabs open, no waitUntil.

If anyone googles this issue 👆 and gets here, this happens when you call `self.skipWaiting` on the already activated (i.e. old) service worker instead of the installed and waiting (i.e. new) service worker.

AFAIK it is not possible to activate the newly installed service worker from within the old one, but you can send the new service worker a message from the old one like so:

```javascript
self.registration.waiting.postMessage({type:'SKIP_WAITING'})
```

However, you probably want to send this message from a client (i.e. a web page) instead. In this case make sure you are sending the correct registartion the message.

**Comment by jeffposnick** [comment] 2020-12-03 14:39
By the way, `workbox-window` v6 has a new helper method, [`messageSkipWaiting()`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-window.Workbox#messageSkipWaiting), that can be used from a web page client and will always use `postMessage({type: 'SKIP_WAITING'})` to the correct service, `waiting` service worker instance.

**Comment by mikelohmann** [comment] 2024-01-31 23:54
> > I see the same thing. Service worker doesn't update even though skipWaiting is called, no other tabs open, no waitUntil.
> 
> If anyone googles this issue 👆 and gets here, this happens when you call `self.skipWaiting` on the already activated (i.e. old) service worker instead of the installed and waiting (i.e. new) service worker.
> 
> AFAIK it is not possible to activate the newly installed service worker from within the old one, but you can send the new service worker a message from the old one like so:
> 
> ```js
> self.registration.waiting.postMessage({type:'SKIP_WAITING'})
> ```
> 
> However, you probably want to send this message from a client (i.e. a web page) instead. In this case make sure you are sending the correct registartion the message.

This did the trick for me!
