### ISSUE TITLE
iOS Safari keeps refreshing on the log in page if SW is active.

### ISSUE THREAD

**Issue by bwk1224** [GoogleChrome/workbox#2260] opened 2019-10-22 23:53 UTC
**Library Affected**:
workbox 4.3.1

**Browser & Platform**:
Safari for iOS 13.1.3

**Issue or Feature Request Description**:
I'm using Workbox using injectManifest method, and it's working great on Windows Chrome & Android Chrome. However I'm having an issue with iOS.

Here's the workflow of my app in .Net Core that uses Google oAuth to allow user sign in.

App Log in Screen -> Sign in with Google button click -> redirects to Google oauth log in page -> user signs in -> Google redirects to my app "https://myapp.com/signin-google" -> App authenticates user and loads a landing page.

The problem is that user is always brought back to the app's log in screen (1st step) when SW is active on iOS Safari. I have tried various routing options, and it seems if I take out setDefaultHandler, the log in works on iOS Safari. But this means "offline" page is not served when the app goes offline.

Does anyone have any suggestions? A copy of my service worker template is attached.

[SW_sample.txt](https://github.com/GoogleChrome/workbox/files/3759133/SW_sample.txt)

**Comment by jeffposnick** [comment] 2019-10-23 14:25
```
workbox.routing.setDefaultHandler(
  new workbox.strategies.NetworkOnly({
    fetchOptions: {credentials: 'include'}
  })
);
```

should be _roughly_ equivalent to not having the router do anything, so it's very strange that removing that bit ends up fixing things for you on iOS Safari.

If it would be possible to share a URL where I could see a live reproduction, that would be ideal.

There's also a community repo set up to track PWA-related bugs specific to given browsers—https://github.com/PWA-POLICE/pwa-bugs. Filing an issue there is not the same thing as, say, a bug report to Apple, but there are folks who are active in that repo that might have had a similar experience.

In terms of a workaround, if you want to get rid of `workbox.routing.setDefaultHandler()` and be more explicit about your routing, while still being able to trigger the offline fallback, here's something that should be roughly equivalent:

```
// Create a network-only strategy that includes credentials.
const networkOnly = new workbox.strategies.NetworkOnly({
  fetchOptions: {credentials: 'include'}
});

// Wrap this strategy in a custom one that .catch()es errors
// and returns the offline HTML response.
const networkWithOfflineFallback = (params) => {
  return networkOnly.handle(params)
    .catch(() => caches.match(FALLBACK_HTML_URL));
}

// Create a route that matches all navigations and uses that custom strategy.
const navigationRoute = new workbox.routing.NavigationRoute(
  networkWithOfflineFallback
);

// Register that navigation route.
workbox.routing.registerRoute(navigationRoute);
```

**Comment by bwk1224** [comment] 2019-10-24 02:10
@jeffposnick Thank you for your detailed explanation and the sample code. Unfortunately the sample code didn't work on iOS Safari. 

It seems as if the login cookie is either not transferred or the service worker is caching the cookie from the 1st sign in attempt, causing invalid matches if user signs out after the SW is installed and then tries to sign in again. It may be similar to "Problem: Cookie/Login isn't shared between Safari and standalone mode" from the PWA-Police, but my problem exists on the Safari browser as well, not just the standalone mode. I'll try the solution provided on that page.

It's very weird that only iOS Safari is having this issue and the app works fine on Windows / Android. 

(I have no problem sharing the live test site with you if I can send a sort of direct msg to you.)

**Comment by jeffposnick** [comment] 2019-10-24 22:15
You can send a Twitter DM with a link to your test site to `@jeffposnick` if that works for you.

**Comment by tomayac** [comment] 2019-10-30 13:44
The underlying issue here is https://github.com/GoogleChrome/workbox/issues/1732. I suggest we close this issue in favor of the linked issue.

**Comment by jeffposnick** [comment] 2019-10-30 13:52
Thanks for diving into this, Tom! We will indeed follow up on #1732.

**Comment by jeffposnick** [comment] 2019-10-31 14:39
Unfortunately, it turns out that while #1732 is a legitimate issue, it's not the underlying root cause here. I think it's just something that @tomayac bumped in to while investigating on iOS (since @bwk1224 did have debug logging turned on).

@bwk1224 has since disabled debug logging, and also did not have the JS console open when originally reproducing this, and they have confirmed that the issue still persists on iOS.

**Comment by tomayac** [comment] 2019-11-04 12:05
I just successfully tried this on iOS 13.2 and the issue might have magically gone away. I didn't even empty my caches or uninstalled the service worker, just re-opened the website in question and logged in. If someone else can successfully reproduce, we can probably close this.

**Comment by bwk1224** [comment] 2019-11-04 12:28
The SW installation on iOS was disabled due to a demo. Sorry about that. I will reenable the sw today.

**Comment by tomayac** [comment] 2019-11-04 12:37
Hah, no magic wonder then :-) Due to #1732 I didn't have the debugger attached, so just blindly assumed the service worker was still there…

**Comment by bwk1224** [comment] 2019-11-04 12:52
The SW on iOS is enabled again. Please let me know if you need any modifications for the testing. I'll keep that site untouched and work on a different url. :)

**Comment by tomayac** [comment] 2019-11-04 12:54
Bad news :-/ The previous behavior is still there in iOS 13.2.

**Comment by tomayac** [comment] 2024-04-25 08:56
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team

**Closed by tomayac** 2024-04-25 08:56 UTC
Labels: Needs More Info, workbox-routing, Browser Compatibility
