### ISSUE TITLE
Geting error: One of the glob patterns doesn't match any files....

### ISSUE THREAD

**Issue by kamalendugarai** [GoogleChrome/workbox#1176] opened 2018-01-16 10:55 UTC
Tried many thing but it still saying "One of the glob patterns doesn't match any files". Please remove or fix the following:

```
{
"globDirectory":"E:\\webpack_practice\\mn6\\dist",
"globPattern": "*.{html, js,css}",
"globIgnores":[
       "node_modules/**/*",
       "workbox-sw.prod.v2.1.2.js",
       "sw.js"
  ]
}
```

**My webpack config file as  #below...**

```js
const path = require("path");
const src_path = path.resolve("src/");
const dist_path = path.resolve("dist/");
const extract_text = require("extract-text-webpack-plugin"); 
const html_plugin = require("html-webpack-plugin");
const commons_chunk = require("webpack/lib/optimize/CommonsChunkPlugin");
const CopyWebpackPlugin = require("copy-webpack-plugin");
const ImageminPlugin = require("imagemin-webpack-plugin").default;
const HardSourceWebpackPlugin = require("hard-source-webpack-plugin");
const Uglify = require("webpack/lib/optimize/UglifyJsPlugin");
const BundleBuddyWebpackPlugin = require("bundle-buddy-webpack-plugin");
const BundleAnalyzerPlugin = require("webpack-bundle-analyzer").BundleAnalyzerPlugin;
const CleanWebpackPlugin = require("clean-webpack-plugin");
const WebpackPwaManifest = require("webpack-pwa-manifest");
const FaviconsWebpackPlugin = require("favicons-webpack-plugin");
const Workbox = require("workbox-webpack-plugin");
const settings={
	plugins:[]
};
const entries={
 	index:path.resolve(src_path,"js/index.js")
}
	settings.entry = entries;
	settings.output = {
		filename:"js/[name].[chunkhash:8].js",
		path:path.resolve(dist_path),
		publicPath:process.env.NODE_ENV == "Client "?"/":""
	};
	settings.devtool= "source-map";
	settings.module={
		rules:[
			{
				test:/.(css|sass)$/,
				use:extract_text.extract({
					fallback:"style-loader",
					use:["css-loader", "postcss-loader", "sass-loader"],
					publicPath:"../"
				})
			},
			{
				test:/.jsx?$/,
				use:"babel-loader",
				exclude:/node-modules/
			},
			{
				test:/.(jpe?g|png|svg|gif)$/,
				use:"url-loader?limit=10000&name=images/[name].[ext]"
			},
			{
				test:/.(ttf|otf|eot|woff|woff2)$/,
				use:"file-loader?name=fonts/[name].[ext]"
			},
			{
				test:/.html$/,
				use:"html-loader?interpolate=require!"
			}
		]
	};
	settings.plugins.push(
		new WebpackPwaManifest({
			name: "My Progressive Web App",
			short_name: "MyPWA",
			description: "My awesome Progressive Web App!",
			background_color: "#cccccc",
			display: "standalone",
			start_url:".",
	    	icons: [
	      		{
	        		src: path.resolve(src_path, "icon.png"),
					sizes: [16, 32, 57, 60,72, 76, 96, 114, 120, 128, 144, 152,180, 192, 256, 384, 512]
	      		}
	    	]
	  		}),
			new FaviconsWebpackPlugin({
				logo: path.resolve(src_path, "icon.png"),
				persistentCache: true,
				inject: true,
				background: "#cccccc",
				title: "My Progressive Web App",
				icons: {
      				android: true,
      				appleIcon: true,
      				appleStartup: true,
      				coast: false,
      				favicons: true,
      				firefox: true,
      				opengraph: false,
      				twitter: true,
      				yandex: false,
      				windows: true
    			}
			}),
 			new CleanWebpackPlugin([dist_path]),
			new extract_text({
 				allChunks: true,
				filename:"css/[name].[contenthash:8].css"
			}),
			function(){
				if(process.env.NODE_ENV == "Production "){
	 				return new Uglify({sourceMap:true})
	 			}else{
	 				return ()=>{};
	 			}
	 		},
	 		function(){
				if(process.env.NODE_ENV == "Production "){
					return new ImageminPlugin({ test: /.(jpe?g|png|gif|svg)$/i })
				}else{
					return ()=>{};
				}
			}(),
			new commons_chunk({async:"commons", children:true, minChunks:4}),
			function(){
			     Object.keys(entries).forEach(function(a){	
			       var flnm = a+".html";
			       var dist_flnm = path.resolve(dist_path, flnm);
			       var src_flnm = path.resolve(src_path, flnm)
				      settings.plugins.push(new html_plugin({
				     	  favicon:false,
 						  hash:true,
					      filename:dist_flnm,
					      template:src_flnm,
					      inject:true,
					      chunks:["commons", a],
					      optimize:{
					       	collapseWhiteSpace:false
					      }
					 }))
			    });
			    return ()=>{};
			}(),
			new HardSourceWebpackPlugin(),
	 		function(){
				if(process.env.NODE_ENV == "Check "){
					return new BundleBuddyWebpackPlugin({sam: true})
				}else{
					return ()=>{};
				}
			}(),
			function(){
				if(process.env.NODE_ENV == "Check "){
					return new BundleAnalyzerPlugin({analyzerPort: 1025})
				}else{
					return ()=>{};
				}
			}(),
			new Workbox({
			    globDirectory: dist_path,
			    globPatterns: ['**/*.{html,js,css}'],
			    swDest: path.join(dist_path, 'sw.js'),
			    clientsClaim: true,
			    skipWaiting: true,
		  	})
	);
	settings.devServer={
		historyApiFallback: true,
		port:9000,
		compress:true,
		open:true,
		https:false,
		open:true
	};
module.exports = settings;
```

I have removed many plugins like hard-source-webpack-plugin, clean-webpack-plugin, webpack-pwa-manifest, favicons-webpack-plugin and tried but issue remain same
Please help me out

**Comment by jeffposnick** [comment] 2018-01-16 19:14
Hello @kamalendugarai—I'm sorry that you're running into issues.

One thing that I find confusing is that your configuration specifies `globPatterns: ['**/*.{html,js,css}']`, but the error message says that the failing `globPattern` is `"*.{html, js,css}"`, without the leading `'**/'` wildcard. Can you confirm that you're definitely passing `'**/*.{html,js,css}'` when configuring the plugin? I'm not sure how to explain that mismatch. Could you also try changing you `globPatterns: ['**/*.{html,js,css}']` to something like `globPatterns: ['**/*.js']` and see what the result is?

Another thing to point out is that the Workbox webpack plugin has been fairly substantially rewritten as part of the current v3 alpha, and if you'd like to give that a try, you might consider that an option. You should be able to switch out your project's `package.json` to depend on `"workbox-webpack-plugin": "3.0.0-alpha.5"` and then change your usage to:

```js
const {GenerateSW} = require('workbox-webpack-plugin');

{
  plugins: [
    // ... other webpack plugins...
    new GenerateSW({clientsClaim: true, skipWaiting: true}),
  ],
}
```

You shouldn't need to configure anything else by default to get the same behavior, as the v3 plugin will automatically get assets from the Webpack compilation pipeline.

**Comment by kamalendugarai** [comment] 2018-01-17 11:22
Thanks @jeffposnick for your help. 
Sorry, that was a typo. 
I have changed globpatterns:['**/*.{html, js, css}'] to globPatterns: ['**/*.js'], now its showing same error with globPatterns: '**/*.js' and if I revert back then its showing the error with globpatterns:'**/*.{html, js, css}'.
I will try the beta version for sure but I would like to solve the issue I raised here also as I do not want to use beta version in my production.

**Comment by jeffposnick** [comment] 2018-01-17 16:17
What's are the full contents of your `dist_path` directory after the build has completed? (With the `Workbox` plugin commented out for the time being.)

**Comment by kamalendugarai** [comment] 2018-01-20 13:36
I tried 'dist' and 'dist/' but its not working either. I had a doubt that something gone wrong in experiment so, I have tried with a new setup but issue remains same.

Can you direct me to a working code base which I can try.

**Comment by jeffposnick** [comment] 2018-01-22 16:36
https://developers.google.com/web/tools/workbox/get-started/webpack uses Workbox 2.x and walks through the process of using the webpack plugin. Does that help?

**Comment by kamalendugarai** [comment] 2018-01-23 12:47
I am using webpack 3.10.0, is it not compatible with workbox!

**Comment by jeffposnick** [comment] 2018-01-23 16:30
webpack 3.10.0 should be compatible with Workbox. (That's our intention, at least.)

There are some known changes to plugins in the webpack 4.x alphas, which we haven't tackled yet (see #1151).

Could you clarify what you mean when you say that webpack 3.10.0 isn't compatible?

**Comment by moimael** [comment] 2018-01-31 15:25
I have the same issue with 3.0 alpha 6

**Comment by gauntface** [comment] 2018-01-31 17:20
@moimael can you provide your config please.

**Comment by moimael** [comment] 2018-02-01 08:47
Sure:

```
new GenerateSW({
        globDirectory: 'public/dist',
        globPatterns: [
          '**/manifest.*.js',
          '**/0.*.js',
          '**/vendor.*.js',
          `**/${app}_vendor.*.js`,
          `**/${app}.*.{js,css}`,
          `**/${app}.html`,
          'fonts/*',
        ],
        directoryIndex: 'landing-pages.html',
        swDest: path.join('public/dist', `${app}-service-worker.js`),
        clientsClaim: true,
        skipWaiting: true,
        dontCacheBustUrlsMatching: '/./',
        runtimeCaching: [
          {
            urlPattern: /^https:\/\/res.cloudinary.com\/universal-avenue\/.*\/v1\/commons\/logo_white.svg/,
            handler: 'cacheFirst',
          },
        ],
      })),
```

**Comment by moimael** [comment] 2018-02-01 08:48
And the specific error i get is this one:

```
4:53:49 PM: Error: One of the glob patterns doesn't match any files. Please remove or fix the following:{
4:53:49 PM:   "globDirectory": "public/dist",
4:53:49 PM:   "globPattern": "**/manifest.*.js",
4:53:49 PM:   "globIgnores": [
4:53:49 PM:     "**/node_modules/**/*"
4:53:49 PM:   ]
4:53:49 PM: }
4:53:49 PM:     at module.exports (/opt/build/repo/node_modules/workbox-build/build/lib/get-file-details.js:52:11)
4:53:49 PM:     at /opt/build/repo/node_modules/workbox-build/build/lib/get-file-manifest-entries.js:87:42
4:53:49 PM:     at Array.reduce (<anonymous>)
4:53:49 PM:     at _callee$ (/opt/build/repo/node_modules/workbox-build/build/lib/get-file-manifest-entries.js:86:42)
4:53:49 PM:     at tryCatch (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:62:40)
4:53:49 PM:     at Generator.invoke [as _invoke] (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:296:22)
4:53:49 PM:     at Generator.prototype.(anonymous function) [as next] (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:114:21)
4:53:49 PM:     at step (/opt/build/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
4:53:49 PM:     at /opt/build/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
4:53:49 PM:     at new Promise (<anonymous>)
4:53:49 PM:     at new F (/opt/build/repo/node_modules/core-js/library/modules/_export.js:35:28)
4:53:49 PM:     at /opt/build/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
4:53:49 PM:     at /opt/build/repo/node_modules/workbox-build/build/lib/get-file-manifest-entries.js:195:18
4:53:49 PM:     at _callee$ (/opt/build/repo/node_modules/workbox-build/build/entry-points/generate-sw-string.js:35:20)
4:53:49 PM:     at tryCatch (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:62:40)
4:53:49 PM:     at Generator.invoke [as _invoke] (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:296:22)
4:53:49 PM:     at Generator.prototype.(anonymous function) [as next] (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:114:21)
4:53:49 PM:     at step (/opt/build/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
4:53:49 PM:     at /opt/build/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
4:53:49 PM:     at new Promise (<anonymous>)
4:53:49 PM:     at new F (/opt/build/repo/node_modules/core-js/library/modules/_export.js:35:28)
4:53:49 PM:     at /opt/build/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
4:53:49 PM:     at generateSWString (/opt/build/repo/node_modules/workbox-build/build/entry-points/generate-sw-string.js:53:17)
4:53:49 PM:     at GenerateSW._callee$ (/opt/build/repo/node_modules/workbox-webpack-plugin/build/generate-sw.js:129:24)
4:53:49 PM:     at tryCatch (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:62:40)
4:53:49 PM:     at Generator.invoke [as _invoke] (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:296:22)
4:53:49 PM:     at Generator.prototype.(anonymous function) [as next] (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:114:21)
4:53:49 PM:     at step (/opt/build/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
4:53:49 PM:     at /opt/build/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
4:53:49 PM:     at <anonymous>
4:53:49 PM: npm ERR! code ELIFECYCLE
4:53:49 PM: npm ERR! errno 1
```

**Comment by gauntface** [comment] 2018-02-01 18:45
@jeffposnick does it make sense to change this to a warning and only through if none of the glob patterns find files? That's probably what I would expect rather than a hard error.

@moimael is there a file you are expecting to match against this `manifest.*.js`?

**Comment by jeffposnick** [comment] 2018-02-01 19:12
@moimael, if you've switched to the v3 prerelease webpack plugin, then using `globPatterns` shouldn't be required anymore, assuming all your assets are part of the webpack compilation. We've got some new docs up at https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#full_generatesw_config explaining that behavior.

@gauntface, I was in favor of raising a hard error because warnings from our build tools will not consistently be exposed to the end user. We tried doing some `console.log()` statements in `sw-precache`, and they ended up being lost amidst the output from the larger build tool that was using our module. (Or just forcibly disabled by `create-react-app`.)

So, in practice, it was a choice between failing or not letting the developer know anything.

**Comment by moimael** [comment] 2018-02-02 09:06
@gauntface Yes I do have a file that matches this. I have `public/dist/js/manifest.1bd239584b430d363eb7.js` (the hash changes between build of course)

@jeffposnick I know but we have a particular setup, our frontend app is divided into "subapps" (ex: admin, landing-pages, ...), each app is independent and is handling one specific business domain. So we generate one service worker per app so people don't have to download dozen of megabytes of assets in the service worker when they visit our landing pages for example. So we create one instance of the plugin per app in our webpack conf, so the globpattern has to be dynamic and not use every asset outputed by webpack.

**Comment by jeffposnick** [comment] 2018-02-02 15:22
What's responsible for writing `public/dist/js/manifest.1bd239584b430d363eb7.js` out to disk? Is it another part of the webpack build process that might run after the Workbox webpack plugin runs? If so, it might be that the file doesn't yet exist on disk at the time Workbox is running.

I don't fully understand the webpack plugin lifecycle and order of events, but the v2/v3 Workbox plugins listen to the `emit` event.

**Comment by moimael** [comment] 2018-02-05 10:04
So the latests plugin I have is the ModuleConcatenationPlugin, and right before workbox runs. So it should catch the manifest file. It is generated at the same time as other chunks with the CommonChunkPlugin.

**Comment by jeffposnick** [comment] 2018-02-05 21:03
Another thing to keep in mind is that the `glob` pattern matching is done against files that have been written to disk. I looked back up at your original `webpack` config and noticed that you're configuring `settings.devServer`—I believe that the webpack dev server maintains its own in-memory filesystem and does not write anything out to disk. Or are you seeing the same failure when using webpack to do a full build, writing to disk?

**Comment by moimael** [comment] 2018-02-06 09:51
This is not my config in the first post ;) We are only enabling workbox for production mode. We are actually using sw-precache with the webpack plugin currently and it works fine with the manifest file. The file is correctly writen to disk before the plugin runs.

**Comment by motosharpley** [comment] 2018-02-15 19:01
I ran into this error with webpack-dev-server build would work but would get the same glob error running webpack-dev-server. My current workaround was to remove clean-webpack-plugin run build first then run webpack-dev-server. Not perfect but it got me past the globs errors. issue #1256 was helpful for me.

**Comment by gauntface** [comment] 2018-02-15 23:46
I'm of the opinion this should change to a warning.

An unexpected build would be preferable to a broken build given the number of people that are hitting this, with frankly unexpected work arounds.

**Comment by gauntface** [comment] 2018-02-15 23:47
**IF ANYONE CAN GIVE US A REPRODUCIBLE EXAMPLE - PLEASE DO**

**Comment by motosharpley** [comment] 2018-02-16 00:17
Thanks @gauntface [here](https://github.com/motosharpley/Preact-Workbox/tree/wrkbox-glob-error) is a basic example master branch works, wrkbox-glob-error branch  produces example error
`npm run build` will compile `npm run dev` will error.
I have not yet tried moving to v3 as was mentioned in issue #1256 but will try to test that out tonight as well.
hope this helps

**Closed** 2018-02-23 00:37 UTC
