### ISSUE TITLE
Create an always upto date workbox.js 

### ISSUE THREAD

**Issue by mayeedwin** [GoogleChrome/workbox#1668] opened 2018-09-28 15:47 UTC
Following the most immediate changes of the **workbox** version, I have found that most workbox made progressive web apps break. This means that as a developer, you have to always worry of updating to the latest version of the **workbox**.

Solution ( I have tried and it's kinda working )

Let's create **workbox-sw.js** file that's always upto date with latest script **import** of the latest version ; eg 

```javascript

importScripts('https://storage.googleapis.com/workbox-cdn/releases/3.6.2/workbox-sw.js');

```

So the devs using workbox will have it done this way.

```javascript

importScripts('https://storage.googleapis.com/workbox-cdn/workbox-sw.js');

```

Learn more about my progressive web apps open source project here >> https://pwafire.org

**Comment by mayeedwin** [comment] 2018-09-28 15:55
Edited ; 😎😎

**Comment by jeffposnick** [comment] 2018-09-28 16:12
> Following the most immediate changes of the workbox version, I have found that most workbox made progressive web apps break. 

Could you please elaborate on that? That's certainly not the intention, and I don't believe I've seen similar reports in the past. What type of breakage are you experiencing?

> So the devs using workbox will have it done this way.
> `importScripts('https://storage.googleapis.com/workbox-cdn/workbox-sw.js');`

This is not possible, due to the way service workers handle checking for updates for dependencies pulled in via `importScripts()`. Unless an imported script's URL changes, there is no guarantee that it will be re-downloaded in a timely manner, or that any changes made to the contents of that URL will trigger a service worker's update. Therefore, it's not recommended to use unversioned URLs along with `importScripts()`.

I'm going to leave this issue open in case you have some reproduction steps for problems triggered by new Workbox versions, but we can't move forward with the other proposal.

**Comment by mayeedwin** [comment] 2018-09-28 16:58
For my workbox test app , I uninstalled it and tried to get it installed again but nothing happened. On updating the service worker script to 3.6.1 ; yey ! It worked. Install prompt showed up

**Comment by jeffposnick** [comment] 2018-09-28 17:07
When you say "uninstalled", what are you referring to?

Do you mean going into the Applications panel of Chrome's DevTools and clicking on the unregister link?

If so, what did you then do to try to get it to install again—reload the page?

And what's the install prompt—is that something that you've added to your web page's user interface?

Sorry for all the questions, but I wanted to understand what's going on, and whether it's something that we have control over via the Workbox release process, or whether it's something specific to the way you're using Workbox independent of our releases.

**Comment by mayeedwin** [comment] 2018-09-28 17:19
The ** Workbox PWA** is live. So uninstalled from my mobile device, visited the URL in chrome web browser again ; the automatic **PWA** install prompt never showed up. On updating the service worker to **workbox 3.6.1** from **3.5.0** ; the install prompt showed up

**Comment by mayeedwin** [comment] 2018-09-29 07:14
> 
> 
> When you say "uninstalled", what are you referring to?
> 
> Do you mean going into the Applications panel of Chrome's DevTools and clicking on the unregister link?
> 
> If so, what did you then do to try to get it to install again—reload the page?
> 
> And what's the install prompt—is that something that you've added to your web page's user interface?
> 
> Sorry for all the questions, but I wanted to understand what's going on, and whether it's something that we have control over via the Workbox release process, or whether it's something specific to the way you're using Workbox independent of our releases.

 uninstalled the Workbox PWA from my mobile device and tried to install it again. The automatic PWA install prompt never showed up. On updating my service worker to the latest version of the workbox, 3.6.1 ; visited the URL again on chrome for Android, the install prompt now showed up and could install my PWA

**Comment by mayeedwin** [comment] 2018-10-03 13:19
@jeffposnick ; so after taking into consideration regarding the use of `importScripts()` ; I went back to my **workbox** test app once more. My pwa worked perfectly after trying what I had suggested above.

One way to test how fast the **dependancies** pull will occur, I have figured out that if the latest version of workbox is imported as in `importScripts('https://storage.googleapis.com/workbox-cdn/workbox-sw.js'); ` and `importScripts('https://storage.googleapis.com/workbox-cdn/workbox-sw.js');` stored in a such away it's never cached or if cached, (network first strategy be used), we shall always have the latest version of workbox service worker re-downloaded in a timely manner via `importScripts('https://storage.googleapis.com/workbox-cdn/workbox-sw.js'); ` 

: ) just concerned so much with having a workbox progressive web app always installed via the automatic install banner prompt.

**Comment by jeffposnick** [comment] 2018-10-03 21:08
> ...The automatic PWA install prompt never showed up...

Okay, thanks for clarifying. I now understand that you're talking about whether or not the Add to Homescreen prompt appears in different scenarios.

This is very much outside of the control of Workbox, and entirely dependent on which browser you're using. It could be that by changing your service worker you "tricked" the browser in question into re-triggering the Add to Homescreen prompt.

So... I'm not sure that there's anything actionable in this issue, and I'm going to close it. If you have questions or concerns about, for example, the latest version of Chrome's Add to Homescreen prompts, then filing a bug using https://bugs.chromium.org/p/chromium/issues/list would be the best course of action.

**Comment by mayeedwin** [comment] 2018-10-03 22:05
I think you really missed my explanation/argument. But it's alright : )
<https://pwafire.org/>

 Google Developer Community
<https://developers.google.com/programs/community/gdg/> |  LinkedIn
<https://www.linkedin.com/in/mayeedwin/> | PWA Fire
<https://pwafire.org> | Microsoft
Interns 4Afrika Graduate
<https://www.microsoft.com/africa/4afrika/interns4afrika/>

**Comment by jeffposnick** [comment] 2018-10-04 00:58
My apologies—I'm trying and failing here. @philipwalton, do you have any insight to offer?

**Comment by philipwalton** [comment] 2018-10-04 20:32
@mayeedwin, if your concern is about keeping Workbox up to date, I'd recommend installing Workbox via npm, and using npm's existing dependency management tools/packages to keep Workbox up to date.

I would not recommend creating an unversioned copy of workbox that always returns the latest version, as then you risk having bugs introduced to your users even in cases where you haven't made any code changes.

**Comment by mayeedwin** [comment] 2018-10-08 20:56
> @mayeedwin, if your concern is about keeping Workbox up to date, I'd recommend installing Workbox via npm, and using npm's existing dependency management tools/packages to keep Workbox up to date.
> 
> I would not recommend creating an unversioned copy of workbox that always returns the latest version, as then you risk having bugs introduced to your users even in cases where you haven't made any code changes.

That's what I have done. I use installed Workbox via npm

**Comment by jeffposnick** [comment] 2018-11-29 22:31
Just wanted to circle back and see if this particular issue is cleared up for you.

**Comment by mayeedwin** [comment] 2018-11-30 15:02
> Just wanted to circle back and see if this particular issue is cleared up for you.

Yeah. Quiet so. Though still working on a demo check the possibility of bugs as suggested by @philipwalton

**Closed** 2018-12-06 20:05 UTC
Labels: Needs More Info
