### ISSUE TITLE
Background Sync - post requests with images are not stored in IndexedDB queue on Mobile Safari (iOS 13.3.1)

### ISSUE THREAD

**Issue by dannyconnell** [GoogleChrome/workbox#2428] opened 2020-03-30 10:32 UTC
**Library Affected**:
workbox-background-sync

**Browser & Platform**:
Mobile Safari (iOS 13.3.1)

**Issue or Feature Request Description**:

I'm having a problem with Workbox Background Sync on iOS Safari.

If I disable the internet and send a post request which contains form data **with an image**, like so: 

```javascript
let formData = new FormData()
formData.append('id', this.post.id)
formData.append('caption', this.post.caption)
formData.append('location', this.post.location)
formData.append('date', this.post.date)
formData.append('favorite', false)
formData.append('file', this.post.photo, this.post.id + '.png')
this.$axios.post(
  'https://myapp.cloudfunctions.net/createPost',
  formData).then(response => { ... }
```

Then the request is **not** successfully added to the IndexedDB.  I can see the database and tables, but they are empty, like so:

<img width="1297" alt="Screenshot 2020-03-26 at 08 56 52" src="https://user-images.githubusercontent.com/5763926/77902862-c5997800-7279-11ea-80c3-08d422cc1fbc.png">

However, if I remove the image from the post request:

```javascript
let formData = new FormData()
formData.append('id', this.post.id)
formData.append('caption', this.post.caption)
formData.append('location', this.post.location)
formData.append('date', this.post.date)
formData.append('favorite', false)
// formData.append('file', this.post.photo, this.post.id + '.png')
this.$axios.post(
  'https://myapp.cloudfunctions.net/createPost',
  formData).then(response => { ... }
```

And then disable internet and trigger the request again, the post request is successfully added to the IndexedDB queue, like so:

<img width="1297" alt="Screenshot 2020-03-26 at 09 00 28" src="https://user-images.githubusercontent.com/5763926/77902896-d34efd80-7279-11ea-89f5-41783d863e05.png">

So, there seems to be an issue with iOS Safari storing the request within IndexedDB - **but only if there is an image / file attached**. 

It all works fine on Chrome and Mobile Chrome, and I'm using the latest version of Workbox (5.1.2).

**Comment by jeffposnick** [comment] 2020-03-30 19:40
CC: @philipwalton 

Also, is there anything logged in the JS console when the request with an image body fails to be added to IDB?

**Comment by philipwalton** [comment] 2020-03-31 00:02
Hmmm, I don't think we have any tests that check storing `FormData` or other complex types in the request body that we run in all browsers.

Given that this works in Chrome, I suspect it's a bug in Safari's IndexedDB implementation, but it'd be nice to know for sure. (And as Jeff said, it'd also be nice to know if any errors are logged to the console.)

**Comment by dannyconnell** [comment] 2020-03-31 10:39
Thanks for replying @jeffposnick @philipwalton.

When I include the image in the request, I see no log whatsoever related to that createPost endpoint. The next log from workbox I see is:

```
workbox – "Precaching did not find a match for https://us-central1-quasagram.cloudfunctions.net/posts"
```

Which is related to something that happens **after** the createPost request.

However, if I remove the image from the post request (as seen in my initial issue above) and then disable the internet and trigger the request again, I do see the following log:

```
workbox – "Request for 'https://myapp.cloudfunctions.net/createPost' has been added to background sync queue 'postsQueue'."
```

So it's as if it is being ignored completely, with no error message. 

Thanks 👍

**Comment by tomsaleeba** [comment] 2020-06-11 07:19
I think this might be caused by the fact that Webkit cannot do Request.arrayBuffer() when the body is FormData. When you try, you get "The operation is not supported" as the error. That call is made by Workbox here: https://github.com/GoogleChrome/workbox/blob/05e6bd631b9cd239b8e44eeff132533430e668cb/packages/workbox-background-sync/src/lib/StorableRequest.ts#L65.

I didn't have this exact issue, but I was crafting requests *in* the Service Worker and then enqueuing them, which still exercises the same Workbox code.

This issue explains a bit more https://bugs.webkit.org/show_bug.cgi?id=212858.

You may also be interested in my test rig that I made to figure out what's going on: https://tomsaleeba.gitlab.io/fiddles/safari-capabilities/. Sorry it's a bit hacky, I needed to figure out what was going on and get things fixed in production so no time to make it nice.

**Comment by dannyconnell** [comment] 2020-06-22 05:19
Thanks @tomsaleeba  👍

**Comment by nyroDev** [comment] 2021-11-08 15:21
In Safari, when formData have a file, the request don't go through Service Worker.
See Bug report on Safari here: https://bugs.webkit.org/show_bug.cgi?id=187461

**Comment by jeffposnick** [comment] 2022-02-09 13:37
Hello all—if you're still seeing issues with the latest Safari releases, and have not seen any movement on the Webkit bugs that you've filed (e.g. https://bugs.webkit.org/show_bug.cgi?id=212858 still seems to be open), you might want to take advantage of this offer: https://twitter.com/jensimmons/status/1491113783838019584

**Comment by tomayac** [comment] 2024-04-25 08:57
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team

**Closed by tomayac** 2024-04-25 08:57 UTC
Labels: workbox-background-sync, Browser Compatibility
