### ISSUE TITLE
Homepage serves Offline page despite being online (Failed to fetch console error)

### ISSUE THREAD

**Issue by chrisblakley** [GoogleChrome/workbox#2006] opened 2019-04-03 19:10 UTC
**Library Affected**: workbox-sw
**Browser & Platform**: Google Chrome 73 (I've noticed this since 67)
(This works fine in other browsers who support Service Worker such as Firefox and Safari)

**Issue Description**:
This is a problem I've been banging my head against for almost a year. I noticed it before I started using Workbox, but then it has appeared again since I began using Workbox. This is a problem that has gone beyond my understanding of "initiators" and behind-the-scenes Chrome functionality.

If I load my website (which uses a Service Worker, now Workbox) [on a subpage](https://gearside.com/nebula/get-started/) and then [visit the home page](https://gearside.com/nebula/), even though I am still online I am served the offline page. The console shows a fetch error but does not provide additional details (so that makes it look like a blocked request– not a failed request). Apparently this is difficult to reproduce, but I've tried multiple computers (home/work) and coworkers computers and can reproduce it every time.

![Screen Shot 2019-04-03 at 2 36 53 PM](https://user-images.githubusercontent.com/6349678/55505095-59614580-5620-11e9-865e-cfc5d90a119c.png)

There is so much information/notes on this problem that I couldn't possibly include everything here, so [please refer to this Github issue](https://github.com/chrisblakley/Nebula/issues/1709).

One common thread in all of these computers is that they are using uBlock Origin. However, after [discussing the problem with them](https://github.com/uBlockOrigin/uBlock-issues/issues/173), I was [directed to Chromium support](https://bugs.chromium.org/p/chromium/issues/detail?id=874173) [where I thought the problem was fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=906185), but unfortunately it is happening again and none of the steps in the Chromium support are fixing it again.

Please note that uBlock Origin is disabled for this website (but I would think that it should work regardless). Another note is that the Service Worker installs successfully, so these resources are not blocked on the initial load/install.

Additional details and support topics:
- https://github.com/chrisblakley/Nebula/issues/1709 (this is where I have been keeping **all** of my notes.
- https://github.com/uBlockOrigin/uBlock-issues/issues/173 (prior to using Workbox)
- https://stackoverflow.com/questions/51833056/fetch-api-inside-service-worker-fails-only-for-the-home-page-when-reloading-it (prior to using Workbox)
- https://bugs.chromium.org/p/chromium/issues/detail?id=874173
- https://bugs.chromium.org/p/chromium/issues/detail?id=906185
  - I thought this one fixed it...

Here are my exact steps to reproduce this:
- In a browser with uBlock Origin installed, view a subpage: https://gearside.com/nebula/get-started/ (and in uBlock, prevent blocking on that website)
- Once the page loads, click the logo to navigate to the homepage or visit this URL: https://gearside.com/nebula/

The Offline page (which is assigned in the SW precache) is shown and the console shows my screenshot above.

I hope I explained enough to illustrate what I'm seeing- I'd appreciate any direction on this. I noticed some other Workbox issues regarding ad blockers, so maybe this is symptomatic of those as well? I would be happy to provide any additional details to help.

Here is my sw.js file: https://gearside.com/nebula/sw.js

On a side-note, I'll actually be at Google I/O this year and this was going to be something I would love to show someone.

**Comment by philipwalton** [comment] 2019-04-03 21:23
Thanks @chrisblakley for the report.

I tried following your steps to reproduce, and I don't get the same results. When I navigate to the home page after following doing what you say in step 1, I arrive at what looks like the regular home page.

One thing I did notice, however, is you have a number of routes that use the `NetworkOnly()` strategy without any plugins, which is [generally not advisable](https://developers.google.com/web/fundamentals/primers/service-workers/high-performance-loading#never_use_a_passthrough_fetch_handler) since it just adds overhead for no reason.

I'm also noticing unhandled exceptions being logged to the console for attempts to cache `POST` requests, so I suspect your `needNetworkRetrieval` handler isn't working as you intend it.

**Comment by chrisblakley** [comment] 2019-04-03 21:29
Thanks for the info- I'm definitely still learning Workbox so I will look into that right away.

**Comment by chrisblakley** [comment] 2019-04-04 13:08
I'm still looking into the "passthrough" fetch problem you mentioned, but in the meantime I've just commented out all of the routes except the StaleWhileRevalidate handler.

When I do the same process as I listed above, here's what I see:
https://drive.google.com/file/d/1SQgwaqGNwQZU_qVb9H4qEZbytMdPsnSs/view

One thing I forgot to mention was that in order for the SW to even install correctly, I need to remove the `HOME_URL` from the precache because of (and what I'm assuming is) the same fetch error. When I uncomment the `HOME_URL` for precache, the Service Worker cannot be installed even on initial load. Here are some screenshots of that:

**sw.js with `HOME_URL` now uncommented for precaching**
![Screen Shot 2019-04-04 at 8 33 07 AM](https://user-images.githubusercontent.com/6349678/55557706-7184a380-56b8-11e9-8526-727162fb6675.png)

**Result on initial load**
_(Workbox debug has been enabled for this)_
![Screen Shot 2019-04-04 at 8 31 56 AM](https://user-images.githubusercontent.com/6349678/55557737-83fedd00-56b8-11e9-913a-f1a9c3b65fc4.png)
The red arrow shows the `Failed to fetch` error, but the orange arrow shows a 200 response for what appears to be the same request: `/nebula/` (which is the home page).

Thanks again for your tips yesterday– I really appreciate your time.

**Comment by chrisblakley** [comment] 2019-05-09 03:44
@jeffposnick Thanks for your time today and allowing me to walk you through my "plight"! I'll do my best to recap some of the notes from our conversation today.

Requests from the service worker are being blocked by an ad blocker (in this case uBlock Origin) even when whitelisted/disabled because the initiator/context is `behind-the-scenes` (requests are _not_ blocked when originating from the hostname itself). We confirmed this when deactivating the extension and could no longer reproduce the problem.

<img width="1436" alt="Screen Shot 2019-05-08 at 8 10 01 PM" src="https://user-images.githubusercontent.com/6349678/57425510-40742300-71d0-11e9-81c7-5333ecbb847b.png">

You mentioned that this Chromium bug seemed similar to this problem:
https://bugs.chromium.org/p/chromium/issues/detail?id=766433

It if helps to note: I can only reproduce this problem on my production site; when I try the same steps from a local install, I cannot recreate the offline page.

I'm going to keep an eye on that Chromium bug, and if there is anything I can provide that would help (additional screenshots, etc.) please let me know!

----

Regarding the `HOME_URL` issue, you mentioned that there may have been some recent updates that may resolve that problem (I have been updating with each Workbox release, but had not tried uncommenting that in a while). I just uncommented it and the service worker installs successfully again, so that part of this problem is resolved! I do still get the request blocked from the original issue, but that no longer prevents the service worker itself from being installed. Thanks so much for noticing that and mentioning it!

**Comment by chrisblakley** [comment] 2019-05-11 18:35
I don't want to preemptively call this resolved, but it seems that installation bugfix that Jeff mentioned in the latest release of Workbox may have also resolved the offline issue I was seeing originally too. I did update Chrome to stable v74 but between those two things happening I have not been able to reproduce this problem at all...

**Comment by jeffposnick** [comment] 2019-05-13 20:17
Glad to hear it, Chris! Based on our conversation, I think that there are two related issues that would be best be tracked independently of Workbox (so I'm going to close this issue):

- There's a rather broad RegExp used by default in uBlock Origin (and likely elsewhere; it looks like it comes from [Easylist](https://github.com/easylist/easylist), which is used in several places) that matches any third-party XMLHttpRequest for a URL that roughly corresponds to any 5+ character `.com` domain, with a path of any 3+ characters, ending in a `/`. That *really* seems broad to me, and likely to come up with a lot of false positives.

- Chrome Extensions that intercept navigation requests made from inside of a service worker end up misattributing those requests as being "third-party", when the navigations made from outside of the service worker are attributed as "first-party". This contributes to why uBlock Origin blocked those requests.

**Closed by jeffposnick** 2019-05-13 20:17 UTC
