### ISSUE TITLE
301 Redirect on HTML page is ignored

### ISSUE THREAD

**Issue by brianchirls** [GoogleChrome/workbox#1664] opened 2018-09-25 19:09 UTC
**Library Affected**:
workbox-sw, workbox-webpack-plugin

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
If a site is hosted on one server and then moved to another, with a 301 permanent redirect on the original, I expect that entering the old URL would cause the browser to redirect to the new URL, where the site will be served.

However, the site continues to display at the old URL. Everything works, using the last version that was deployed on the original URL. It appears the old service worker script continues to run, though it will no longer run a new service worker script because it's considered unsafe on a redirect to a different host.

**Example Link**

I have an example. The old url is https://morph.datavized.com and the new one is https://app.morph.graphics - though you won't see the bad behavior unless you loaded the former before the redirect was set up. If you load it the first time, before the service worker has been installed, the redirect will work.

All the code is here:
https://github.com/datavized/morph/

Thanks

**Comment by jeffposnick** [comment] 2018-10-04 20:33
That sounds close enough to https://github.com/GoogleChrome/workbox/issues/1677 that I'm going to assume there's the same root cause; closing in favor of that one.

**Closed by jeffposnick** 2018-10-04 20:33 UTC
