### ISSUE TITLE
CDN publishing fails when part of the larger gulp publish chain

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#1165] opened 2018-01-09 18:41 UTC
This is the error thrown by `gulp publish-github` when we do a release via `gulp publish` and all steps are chained.

```
[10:27:06] 'publish-github:generate-from-tags' errored after 1.05 min
[10:27:06] TypeError: Cannot read property 'objectMode' of undefined
    at Readable.Writable.write (/usr/local/google/home/mattgaunt/Projects/Code/workbox/node_modules/readable-stream/lib/_stream_writable.js:305:45)
    at ReadStream.ondata (_stream_readable.js:628:20)
    at emitOne (events.js:115:13)
    at ReadStream.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at ReadStream.Readable.push (_stream_readable.js:197:10)
    at onread (fs.js:2003:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:664:17)
```

**Comment by jeffposnick** [comment] 2018-01-16 21:15
I was digging into this a bit and it sounds like it could be the same thing as https://github.com/archiverjs/node-archiver/issues/288

It's unfortunate that the rejected promise within the `gulp` task leads to a real loss of stack context when the error is logged, but the `'publish-github:generate-from-tags` task does call` archiver`, so that's one similarity. And that other bug report also involves a failure when the archive is created inside of a promise chain (in that case, Bluebird's promises).

I'm still working out how to reproduce this without running through the actual publishing workflow, ensuring that we don't end up accidentally publishing things on `npm` and GitHub, in order to test possible solutions.

**Comment by jeffposnick** [comment] 2018-01-16 21:36
It turns out that the `archiver` module already returns a promise from its `finalize()` method: https://github.com/archiverjs/node-archiver/blob/d43f922abcf2e9b407fa45591e0e8665fc0f8786/lib/core.js#L762-L795

(This isn't mentioned in [the docs](https://archiverjs.com/docs/Archiver.html#finalize), but I filed a PR to fix that: https://github.com/archiverjs/node-archiver/pull/306.)

I'm going to put together a PR that refactors how we use `archiver` to take advantage of that `Promise`. I'm not sure whether it will fix the issue we're seeing, but it sounds like a good approach anyway.

**Comment by jeffposnick** [comment] 2018-01-24 16:34
Boo. Just tried another `gulp publish` with #1179 merged, and I'm getting the exact same error.

**Comment by jeffposnick** [comment] 2018-01-24 16:40
For future reference, while this bug is still open, you can resume the publishing process after this failure by running the following two commands:

```sh
$ gulp publish:cdn+git
$ gulp publish-demos
```

**Comment by gauntface** [comment] 2018-02-13 01:14
This changed (sorry - but for the better).

Now run `gulp publish` this will do lerna process, and then run `gulp publish-assets`, which will do the github release package, publish to CDN and publish the demos.

> Note: The `gulp publish` command will also log a message to run the second command - in case you forget.

**Comment by jeffposnick** [comment] 2021-08-11 18:48
FWIW, if you skip the test suite (`gulp publish --distTag=latest --skipTests`) then CDN publishing succeeds. So the current issue seems to be due to an interplay between our test runner and the CDN upload script.

**Comment by tomayac** [comment] 2024-04-25 09:01
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team

**Closed by tomayac** 2024-04-25 09:01 UTC
Labels: Bug, Infrastructure
