### ISSUE TITLE
InjectManifestPlugin with local workbox not gets served over webpack-dev-server

### ISSUE THREAD

**Issue by wagner-daniel** [GoogleChrome/workbox#1596] opened 2018-08-06 13:27 UTC
I have the following webpack config

```
new InjectManifest({
    importWorkboxFrom: 'local',
    swSrc: './app/src/service-worker.js',
    include: /\.(html|js|svg)$/
})
```

When I run the build all workbox files are in the folder workbox-v3.4.1

But with webpack-dev-server I get a 404 when the service-worker.js tries to load

https://localhost:8080/workbox-v3.4.1/workbox-sw.js

As you can see I use workbox-webpack-plugin version 3.4.1

**Comment by wagner-daniel** [comment] 2018-08-15 17:35
Thanks for your reply :)

My `app/src/service-worker.js` content:

```
workbox.skipWaiting();
workbox.clientsClaim();

workbox.core.setCacheNameDetails({
    prefix: 'sw-cache',
    suffix: 'v1',
    precache: 'precache',
    runtime: 'runtime'
});

workbox.precaching.precacheAndRoute(self.__precacheManifest);
```
The InjectManifest plugin transforms it to this

```
importScripts("/precache-manifest.54d94be072048053343ed6883bb58326.js", "/workbox-v3.4.1/workbox-sw.js");
workbox.setConfig({modulePathPrefix: "/workbox-v3.4.1"});
workbox.skipWaiting();
workbox.clientsClaim();

workbox.core.setCacheNameDetails({
    prefix: 'sw-cache',
    suffix: 'v1',
    precache: 'precache',
    runtime: 'runtime'
});

workbox.precaching.precacheAndRoute(self.__precacheManifest);
```

My `webpack-dev-server` serves over https://localhost:8080.

When the service worker tries to load workbox via this url:

https://localhost:8080/workbox-v3.4.1/workbox-sw.js

But the browser gets a 404 error for this url.

When I build the project (Only using webpack, not the dev server) and upload it to my production server, it loads workbox via this url (I replaced the url with example.com here):

https://example.com/workbox-v3.4.1/workbox-sw.js

It works fine.

I think the whole workbox library gets not served via the `webpack-dev-server` and only copied in when I build the project.

**Comment by Dabolus** [comment] 2018-08-19 06:59
Same issue here. I think the problem is that Workbox is downloading its files on the real filesystem instead of using `memory-fs`. In fact, during development I get a `build` directory (that is my Webpack config destination folder) containing only Workbox files, while everything else is correctly using `memory-fs`:

<img width="411" alt="Workbox downloading files on real fs" src="https://user-images.githubusercontent.com/28671340/44306346-2a49dc80-a38d-11e8-9838-65efc3c26004.png">

Probably this is due to [this file](https://github.com/GoogleChrome/workbox/blob/1c27178e0780adff87a6038b51b58604fa3ceb34/packages/workbox-build/src/lib/copy-workbox-libraries.js), that simply copies Workbox files on the filesystem.

By the way, the issue seems to be only relative to the `local` option. When importing from `cdn` everything works like a charm (including the precache manifest, that gets correctly generated into `memory-fs`)

**Comment by jeffposnick** [comment] 2018-08-20 18:48
Thanks for debugging further. Moving `importWorkboxFrom: 'local'` over to the `webpack` asset pipeline is tracked in https://github.com/GoogleChrome/workbox/issues/1338, and is planned for the future v4 release.

I'm going to close this in favor of that issue.

**Closed by jeffposnick** 2018-08-20 18:48 UTC
Labels: Developer Experience, Needs More Info, workbox-sw, workbox-webpack-plugin
