### ISSUE TITLE
"filePaths" property instead of "manifestEntries" property in the result returned by getManifest

### ISSUE THREAD

**Issue by zhansingsong** [GoogleChrome/workbox#2565] opened 2020-07-03 06:52 UTC
**Library Affected**:
*workbox-build*

**Browser & Platform**:
*node*

**Issue or Feature Request Description**:

[**getManifest** in Reference Docs](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.getManifest)
> ### getManifest
> ASYNC   STATIC
> getManifest(config) returns Promise containing {count: number, **filePaths: Array of string**, size: number, warnings: Array of string}

However, in [`get-manifest.js` source code](https://github.com/GoogleChrome/workbox/blob/v5.1.2/packages/workbox-build/src/get-manifest.js):

```js
async function getManifest(config) {
  const options = validate(config, getManifestSchema);

  const {manifestEntries, count, size, warnings} =
    await getFileManifestEntries(options);

  return {manifestEntries, count, size, warnings};
}
```
Test output:
```
{ manifestEntries: 
   [ { url: 'build/sw.js',
       revision: 'fde80726529bbfdf160fcc131c0667b5' },
     { url: 'build/workbox-9a0ba6e5.js',
       revision: '18cdb5d571007a46d7617e537b7cb07c' },
     { url: 'dev/s.css',
       revision: 'd9d499ac6c7eb18cddfde5a9c64e8bd5' },
     { url: 'ignore/test.js',
       revision: '1a4752c5fb593e55ff7bbd77b4bac5c3' },
     { url: 'index.js',
       revision: '68ae3f96547919a1b1dd9ca5d2016461' },
     { url: 'other/test.js',
       revision: '1a4752c5fb593e55ff7bbd77b4bac5c3' },
     { url: '/app-shell',
       revision: 'b4c7b8dd93539e474a2d95b1ac876bde' } ],
  count: 7,
  size: 197605,
  warnings: [ 'zhansingsong' ] }
```

I have checked `generateSW()` and `injectManifest()` are  both `"filePaths"` property,  not `"manifestEntries"` property.

**Comment by jeffposnick** [comment] 2020-07-06 18:56
Apologies; that's a mistake in the JSDoc and the generated documentation. The intended behavior is what's actually implemented, with `manifestEntries` as one of the returned properties, not `filePaths`.

**Comment by jeffposnick** [comment] 2020-07-06 18:57
(This was fixed in https://github.com/GoogleChrome/workbox/pull/2429 but the old text hasn't been replaced via a republish yet.)

**Closed as completed by jeffposnick** 2020-07-06 18:57 UTC
