### ISSUE TITLE
Background sync demo is not working

### ISSUE THREAD

**Issue by rajagopalx** [GoogleChrome/workbox#1282] opened 2018-02-06 11:48 UTC
I think demo in https://workbox-demos.firebaseapp.com/demo/workbox-background-sync/  is not working.

**Browser & Platform**:
Google Chrome  63.0.3239.132 on Windows 10

**Comment by gauntface** [comment] 2018-02-06 14:39
@rajagopalx could you provide:

1. Reproduction steps - what did you do
1. What did you expect to happen
1. What actually happened

**Comment by rajagopalx** [comment] 2018-02-11 08:19
**Reproduction Steps:**

1.  Disable the internet connection
2.  Click Make request button. The request will fail.
3.  Enable the internet connection
4.  Nothing happens in the network tab.

**What I expect to happen**

While turning on the internet, background sync will initiate fetch event again. But nothing happens.

**Comment by prateekbh** [comment] 2018-02-11 13:01
@rajagopalx just confirming are you physically disconnecting internet or dev tools or some other tool?

**Comment by rajagopalx** [comment] 2018-02-11 14:54
On windows 10, I just disable the ethernet connection.

![disable](https://user-images.githubusercontent.com/10378178/36074680-957bbcb6-0f69-11e8-90ac-234c88553e78.PNG)

**Comment by prateekbh** [comment] 2018-02-11 18:03
can u try, just unplugging may be?
because I cross checked it right now and it seems to work
<img width="666" alt="screen shot 2018-02-11 at 7 01 47 pm" src="https://user-images.githubusercontent.com/5960497/36076568-1a594e78-0f5e-11e8-9ada-fb65edd4dc78.png">

**Comment by rajagopalx** [comment] 2018-02-12 00:41
It's working (checked with both unplug and disable).  It's not get synced immediately when turn on the internet. It takes time to sync (No exact time, Sometimes trigger only 5 minutes after resuming the internet).  Is it normal?

**Comment by prateekbh** [comment] 2018-02-12 03:43
for a failed background sync replay it is, not for the first time I guess.

**Comment by gauntface** [comment] 2018-02-21 21:05
@rajagopalx the delay in the 'sync' event is expected and controlled by the browser.

Since the demo works and the demo and module page have improved instructions I'm going to close this issue.

**Closed by gauntface** 2018-02-21 21:05 UTC
