### ISSUE TITLE
Old version not changing to new version without hard refresh while dev window is open.

### ISSUE THREAD

**Issue by pirovorster** [GoogleChrome/workbox#1603] opened 2018-08-11 16:03 UTC
I have posted the following question on Stackoverflow with a bounty (until it expired), with no responses

https://stackoverflow.com/questions/51583964/workbox-old-version-not-changing-to-new-version

I am using workbox to cache my single page application. My webpack settings looks as follows:

    new workboxPlugin({
    	globDirectory: dist,
    	globPatterns: ['**/*.js', '**/*.html'],
    	swDest: path.join(dist, 'sw.js'),
    	clientsClaim: true,
    	skipWaiting: true,	
    	}),

For the most part it works. However sometimes some devices refuse to update. (I don't know if it effects all browsers but specifically Chrome: Version 67.0.3396.99 is effected)
One scenario:

 1. I refresh the page a few times with ctrl - F5. But the new version does not appear
 2. I open chrome development tools and do a ctrl - F5. Then it works
 3. If I press normal F5 (with or without devtools open) it reverts to the previous version of the application. In addition, if I close the dev tools and press ctrl - F5 it also reverts.

Other devices upgrade flawlessly.

**Comment by jeffposnick** [comment] 2018-08-13 14:38
What you describe makes me wonder whether one of a few things is happening:

- There's something going on with your web server's HTTP `Cache-Control` headers that's causing assets to be added to the browser cache, and Workbox believes that the requests for those assets do not need to be cache-busted.

- You're on a device that is almost out of free storage, and your attempts to update previously cached entries are failing due to `QuotaExceeded` errors.

Could you pass along a few pieces of additional information if you're able to reproduce the issue?

1. A screenshot or an `.har` archive of the relevant HTTP traffic reported in the [Network panel](https://developers.google.com/web/tools/chrome-devtools/network-performance/resource-loading) of Chrome DevTools.

2. A copy of any errors that might be logged in the [JS console](https://developers.google.com/web/tools/chrome-devtools/console/).

3. The contents of your generated precache manifest file, ideally both the before (pre-update) and after (post-update).

**Comment by pirovorster** [comment] 2018-08-13 17:51
Thanks for the help. 

I will post the required info when the issue happens again. Unfortunately it does not always happen. Will try to reproduce it asap.

**Comment by pirovorster** [comment] 2018-08-20 22:32
I have not been able to reproduce the issue. Apologies for the delay. Will let you know as soon as it happens again.

**Comment by jeffposnick** [comment] 2018-09-24 14:44
Thanks for providing those details.

The `.har` archive shows that your new service worker file was downloaded, but it doesn't include the network requests for the precached assets. Did you see any errors logged in the JS console at the time?

Also, I noticed that you're using Workbox `2.1.3`. We're now up to Workbox `3.6.1`, and while I'm not aware of any specific bugs that were fixed in between the two releases that would explain what you're seeing, I'd recommend [upgrading](https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v2) anyway—it will make it easier to debug this if you're on the latest codebase.

**Comment by pirovorster** [comment] 2018-11-05 19:39
Hi @jeffposnick 

Thanks for the help.

Happened again today. There are no JS console errors. Except for the upgrade is there anything else I can provide you that might help debugging.

**Comment by pirovorster** [comment] 2018-11-05 20:16
I have upgraded to the latest version. Will post here if I have any further issues.

**Comment by jeffposnick** [comment] 2019-03-20 20:51
Closing due to lack of activity—if the original poster is still able to reproduce with the latest Workbox release, we can reopen.

**Closed by jeffposnick** 2019-03-20 20:51 UTC
Labels: workbox-precaching, workbox-webpack-plugin
