### ISSUE TITLE
workbox-webpack-plugin version 5 upgrade errors

### ISSUE THREAD

**Issue by activebiz** [GoogleChrome/workbox#2348] opened 2020-02-03 20:38 UTC
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*all browsers".*

**Issue or Feature Request Description**:
*upgrading to workbox version 5 errors*

I have upgraded recently upgraded workbox to version 5 . The workbox is used using webpack. The webpack config is as follows:

```
new workboxPlugin.GenerateSW({
		swDest: 'sw.js',
		clientsClaim: true,
		skipWaiting: true,
	})
```

The sw in the app is configured as follows:

```
function init() {
  if (process.env.NODE_ENV === "development" && "serviceWorker" in navigator) {
    window.addEventListener("load", () => {
      navigator.serviceWorker.register("/sw.js").then((registration) => {
        logger.debug("SW registered: ", registration);
      }).catch((registrationError) => {
        logger.debug("SW registration failed: ", registrationError);
      });
    });
  }
}
```

It was working fine in v4.3.1 (workbox-webpack-plugin) but ever since its upgraded to v5 it started to give following erros (lots of them) when start the webpack.

```
..................
122:5-18
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/TimePickerToolbar-81100fab.js] ..../node_modules/@material-ui/pickers/esm/TimePickerToolbar-81100fab.js 131:6-19
    harmony side effect evaluation react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 1:0-99
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 44:9-22
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 67:9-22
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 73:13-26
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 76:6-19
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 80:18-31
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 83:37-50
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 86:33-46
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 89:30-43
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 120:58-67
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 120:70-85
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 131:23-29
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 170:9-22
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 170:23-31
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 170:39-52
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 170:107-120
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 219:12-18
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 223:9-22
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 223:23-31
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 223:39-52
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 225:7-20
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 258:21-34
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 264:9-22
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js] ..../node_modules/@material-ui/pickers/esm/Wrapper-241966d7.js 266:5-18
    harmony side effect evaluation react [./node_modules/@material-ui/pickers/esm/index.js] ..../node_modules/@material-ui/pickers/esm/index.js 2:0-15
    harmony side effect evaluation react [./node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js] ..../node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js 2:0-120
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js] ..../node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js 43:9-22
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js] ..../node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js 60:9-22
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js] ..../node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js 63:13-26
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js] ..../node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js 122:9-22
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js] ..../node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js 140:27-34
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js] ..../node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js 145:9-22
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js] ..../node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js 166:9-23
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js] ..../node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js 166:54-68
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js] ..../node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js 168:6-20
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js] ..../node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js 314:18-25
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js] ..../node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js 324:9-22
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js] ..../node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js 333:11-24
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js] ..../node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js 341:104-117
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js] ..../node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js 343:31-44
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js] ..../node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js 352:16-29
    harmony import specifier react [./node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js] ..../node_modules/@material-ui/pickers/esm/makePickerWithSta
..........................
```

Its a simple configuration, any idea?

**Comment by philipwalton** [comment] 2020-02-05 23:00
Can you share more details about your webpack config? Most of those errors seem to be coming from `@material-ui`, and Workbox is not mentioned anywhere in that stack trace.

I suspect the problem is not with Workbox itself, but perhaps an issue with how some other package is integrating with Workbox. In order to debug further, though, we'd have to know more about your webpack config.

**Comment by activebiz** [comment] 2020-02-07 13:01
Thanks @philipwalton 
Here's the webpack.config.js

```"use strict";
const webpack = require("webpack");
const path = require("path");
const fs = require("fs");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const CopyWebpackPlugin = require("copy-webpack-plugin");
const ForkTsCheckerWebpackPlugin = require("fork-ts-checker-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const workboxPlugin = require("workbox-webpack-plugin");

module.exports = (environment) => {
	return {
		mode: "development",
		entry: `./app/Index`,
		devtool: "source-map",
		output: {
			path: environment.distBasePath,
			filename: "bundle.js"
		},
		resolve: {
			extensions: [".ts", ".tsx", ".js", ".jsx", ".json", ".scss"],
			alias: {
				"react-dom": "@hot-loader/react-dom"
			  }
		},
		module: {
			rules: getRules(environment)
		},
		devServer: getServer(environment),
		plugins: getPlugins(environment),
		target: "web",
		performance: {
			hints: false
		},
		
	}
};

const getServerStatSettings = (environment) => {
	return {
		// Add asset Information
		assets: true,
		// Sort assets by a field
		// assetsSort: "field",
		// Add information about cached (not built) modules
		cached: true,
		// Add children information
		children: true,
		// Add chunk information (setting this to `false` allows for a less verbose output)
		chunks: true,
		// Add built modules information to chunk information
		chunkModules: true,
		// Add the origins of chunks and chunk merging info
		chunkOrigins: true,
		// Sort the chunks by a field
		// chunksSort: "field",
		// Context directory for request shortening
		context: `../${environment.appFolder}/`,
		// `webpack --colors` equivalent
		colors: true,
		// Add errors
		errors: true,
		// Add details to errors (like resolving log)
		errorDetails: true,
		// Add the hash of the compilation
		hash: true,
		// Add built modules information
		modules: true,
		// Sort the modules by a field
		// modulesSort: "field",
		// Add public path information
		publicPath: true,
		// Add information about the reasons why modules are included
		reasons: true,
		// Add the source code of modules
		source: true,
		// Add timing information
		timings: true,
		// Add webpack version information
		version: true,
		// Add warnings
		warnings: false
	};
}

const getServer = (environment) => {
	return {
		contentBase: environment.distBasePath,
		compress: true,
		// do not print bundle build stats
		noInfo: true,
		// enable HMR
		hot: true,
		// embed the webpack-dev-server runtime into the bundle
		inline: true,
		// serve index.html in place of 404 responses to allow HTML5 history
		historyApiFallback: {
			index: path.resolve(environment.distFolder, "index.html")
		},
		https: {
			key: fs.readFileSync(path.resolve(environment.sslPath, "key.pem")),
			cert: fs.readFileSync(path.resolve(environment.sslPath, "server.crt")),
			ca: fs.readFileSync(path.resolve(environment.sslPath, "cert.pem")),
		},
		port: environment.port,
		host: environment.host,
		watchContentBase: true,
		stats: getServerStatSettings(environment),
		overlay: {
			warnings: true,
			errors: true
		}
	}
}

const getPlugins = (environment) => {
	let plugins = [];
	plugins.push(new webpack.optimize.OccurrenceOrderPlugin());
	// plugins.push(new webpack.NoEmitOnErrorsPlugin());
	plugins.push(new MiniCssExtractPlugin({
		// Options similar to the same options in webpackOptions.output
		// both options are optional
		filename: "[name].css",
		chunkFilename: "[id].css"
	}));
	plugins.push(new webpack.NamedModulesPlugin());
	plugins.push(new webpack.DefinePlugin({
		"process.env": {
			NODE_ENV: JSON.stringify(environment.build),
			PLATFORM: JSON.stringify(environment.platform),
			HOST: JSON.stringify(environment.host),
			PORT: JSON.stringify(environment.port),
			VERSION: JSON.stringify(environment.version)
		}
	}));
	plugins.push(new HtmlWebpackPlugin({
		template: `./${environment.appFolder}/template.html`,
		files: {
			css: ["style.css"],
			js: ["bundle.js"],
		}
	}));
	plugins.push(new CopyWebpackPlugin([{
		from: "favicon.ico",
		to: "favicon.ico"
	},
	{
		from: `${environment.rootPath}/server.js`,
		to: "../server.js"
	},
	{
		from: `${environment.sslPath}/activebiz.pfx`,
		to: "../ssl/activebiz.pfx"
	},
	{
		from: environment.config,
		to: "app.config.json"
	},
	{
		from: `${environment.rootPath}/server.config.json`,
		to: "../server.config.json"
	},
	{
		from: `./${environment.appFolder}/robots.txt`,
		to: "robots.txt"
	}
	]));
	// plugins.push(new webpack.optimize.CommonsChunkPlugin({
	// 	names: ["vendors"]
	// }));
	plugins.push(new ForkTsCheckerWebpackPlugin({
		eslint: true,
		checkSyntacticErrors: true
	}));
	plugins.push(new workboxPlugin.GenerateSW({
		swDest: 'sw.js',
		clientsClaim: true,
		skipWaiting: true,
	}));
	return plugins;
}

const getRules = (environment) => {

	return [
		{
			test: /\.ts(x?)$/,
			exclude: /node_modules/,
			include: environment.appBasePath,
		},
		{
			test: /\.ts(x?)$/,
			use: [
				{
					loader: "ts-loader", options:
					{
						happyPackMode: true,
						transpileOnly: true
					}
				}
			],
			exclude: /node_modules/
		},
		{
			test: /\.mjs$/,
			include: /node_modules/,
			type: "javascript/auto",
		},
		{
			test: /\.css$/,
			use: [
				{
					loader: MiniCssExtractPlugin.loader,
					options: {
						// you can specify a publicPath here
						// by default it use publicPath in webpackOptions.output
						publicPath: '../'
					}
				},
				"css-loader"
			]
		},
		{
			test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
			exclude: /(node_modules|bower_components)/,
			loader: "file-loader"
		},
		{
			test: /\.(woff|woff2)$/,
			exclude: /(node_modules|bower_components)/,
			use: [
				{
					loader: "url-loader",
					options: {
						limit: 5000,
						prefix: "font"
					}
				}
			]
		},
		{
			test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
			exclude: /(node_modules|bower_components)/,
			use: [
				{
					loader: "url-loader",
					options: {
						limit: 10000,
						mimetype: "application/octet-stream"
					}
				}
			]
		},
		{
			test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
			exclude: /(node_modules|bower_components)/,
			use: [
				{
					loader: "url-loader",
					options: {
						limit: 10000,
						mimetype: "image/svg+xml"
					}
				}
			]
		},
		{
			test: /\.(png|jpg|gif)$/i,
			// exclude: /(node_modules|bower_components)/,
			use: [
				{
					loader: "url-loader",
					options: {
						limit: 8192
					}
				}
			]
		}
	];
}```

**Comment by philipwalton** [comment] 2020-02-07 18:33
Hmmm, thanks for the reply, but I'm still not sure we have enough information to help.

It seems very unlikely to me that everything was building perfectly and then _just_ upgrading `workbox-webpack-plugin` caused the above errors (especially since those errors don't come from any Workbox packages).

Are you sure it was just Workbox that was updated? Could it have been that you updated several dependencies at the same time? Maybe check the Git history of your `package-lock.json` file?

**Comment by activebiz** [comment] 2020-02-08 08:34
I have deleted the package-lock.json and then only updated the workbox-webpack-plugin (no other node moduels updated) and it fails. As soon as I revert it back to the v4 it works fine. So I cant see any other package being a problem as no other package is updated!
btw the workbox-webpack-plugin is pinned down to 5.0.0.

**Comment by philipwalton** [comment] 2020-02-10 22:22
@jeffposnick any ideas?

**Comment by jeffposnick** [comment] 2020-02-11 15:20
The only other place I can see something along the lines of that logged output on the Internet is https://github.com/edmorley/testcase-react-hot-loader-sideEffects/blob/master/build.log, which points back to https://github.com/gaearon/react-hot-loader/issues/1095

You're also using `@hot-loader/react-dom`, so that does sound similar.

Let's take a step back for a second—the initial code you posted indicated that you're only registering your service worker when `process.env.NODE_ENV === "development"`, and in development mode, you're also using `webpack-dev-server` and hot module reloading. Neither of those things is going to play nicely with a service worker that aggressively caches assets in the webpack compilation pipeline. I could imagine a scenario in which the service worker returns an previously cached instance of a compiled `webpack` asset when the HMR logic requests what should be a newer instance, and that in turn leading to some runtime errors.

I don't know why there would be a specific difference between Workbox v4 and v5 in this scenario, but my general suggestion would be not to register a service worker that aggressively caches things while also trying to use HMR and `webpack-dev-server`. I'd instead do your local development without a service worker, or with an empty service worker that will act as a no-op, and only register your Workbox-generated service worker in staging/production, outside of a HMR scenario.

**Comment by jeffposnick** [comment] 2020-06-01 16:03
I'm closing this for now as I'm not sure that's there's anything actionable on our end. If this is something that you're up for debugging further, we can reopen.

**Closed by jeffposnick** 2020-06-01 16:03 UTC
Labels: Needs More Info, workbox-webpack-plugin
