### ISSUE TITLE
Issue with multiple simultaneous Range: requests for the same URL

### ISSUE THREAD

**Issue by CryogenicPlanet** [GoogleChrome/workbox#2948] opened 2021-09-30 03:41 UTC
**Library Affected**:
`workbox-range-requests, workbox-core`

**Browser & Platform**:
Brave Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (64-bit), Google Chrome    93.0.4577.82 (Official Build) (64-bit)

**Issue or Feature Request Description**:

We have a bug with caching and retrieving media from a service worker

The goal is to be able to intercept a request made from the video tag and serve it from a cache.

We are having problems with this for larger files of about 100mb+

We have looked at https://github.com/GoogleChrome/workbox/issues/1663#issuecomment-448755945 and https://github.com/GoogleChrome/workbox/issues/2382

But are experiencing a bug where the media is buffering for a long time with the service worker, especially during scrubbing and wanted to combat this.

This also seems like a bug specifically only on Chrome and not in Firefox, it works as expected in firefox

## Screenshots

These requests are taking forever to load when scrubbing, especially while moving back and forth

![image](https://user-images.githubusercontent.com/10355479/135380410-508ae3e0-e7e0-488a-b807-5d37116d5658.png)
![image](https://user-images.githubusercontent.com/10355479/135380413-4b6b84fb-c858-4782-a2de-71f2c4f279ef.png)

---

<details>
<summary><b>Workbox setup code</b></summary>

The code for our service worker is in [`service-worker.setup.js`](https://github.com/modfy/service-worker-media-bug/blob/master/service-worker.setup.js)

```js
/* eslint-disable no-restricted-globals */
const { RangeRequestsPlugin } = require('workbox-range-requests')
const { registerRoute } = require('workbox-routing')
const { clientsClaim, skipWaiting } = require('workbox-core')
const { CacheFirst } = require('workbox-strategies/CacheFirst')
const {
  CacheableResponsePlugin
} = require('workbox-cacheable-response/CacheableResponsePlugin')

const { precacheAndRoute } = require('workbox-precaching/precacheAndRoute')

skipWaiting()
clientsClaim()

registerRoute(
  // Match /api/asset/<anything except getSignedUploadURL>
  ({ url }) => url.toString().match(/\/api\/asset\/(?!getSignedUploadURL).*/),
  new CacheFirst({
    cacheName: 'modfy-assets',
    matchOptions: {
      // TODO: I don't know what this does, research it
      ignoreVary: true,
      ignoreSearch: true
    },
    plugins: [
      // Only cache responses with status code 200 that have data from the signed
      // URL fetched
      new CacheableResponsePlugin({
        statuses: [200]
      }),
      new RangeRequestsPlugin()
    ]
  })
)

// eslint-disable-next-line no-restricted-globals
precacheAndRoute(self.__WB_MANIFEST || [])

self.onmessage = (event) => {
  if (event.data === 'claimMe') {
    self.clients.claim()
  } else if (event.data === 'isMultiplayer=true') {
    self.isMultiplayer = true
  } else if (event.data === 'isMultiplayer=false') {
    self.isMultiplayer = false
  }
}
```
</details>

---

Repo for reproduction https://github.com/modfy/service-worker-media-bug
Public link https://service-worker-testing.vercel.app

**Comment by jeffposnick** [comment] 2021-10-08 18:14
Apologies that this is affecting you, and thank you for reporting and providing a full reproduction.

When I visit https://service-worker-testing.vercel.app and scrub around the first video I can reproduce some eventual failures. Note that what I'm seeing isn't really slowness; I'm seeing Workbox's service worker code respond to a range request with a HTTP 416 instead of HTTP 206 due to an exception thrown at line

https://github.com/GoogleChrome/workbox/blob/8afb37210d8f4fe62847f4e80e42fc95bced4895/packages/workbox-range-requests/src/createPartialResponse.ts#L65

That `await originalResponse.blob()` throws a `TypeError: Failed to fetch`, based on the console logs. I wasn't aware that obtaining the body of a `Response` (which in this case corresponds to a Cache Storage API entry) as a `Blob` could potentially throw `TypeError: Failed to fetch`.

I wonder if the trigger for this error is that when you're scrubbing around a video, there might be multiple in-flight requests for the same cached media `Response`, each with different `Range:` headers, and Workbox ends up attempting to get the `Blob` body associated with the same underlying cached `Response` simultaneously in different asynchronous `fetch` event handler invocations? In each invocation, the `Response` is retrieved from a distinct `cache.match()` call, but I don't fully understand what might be happening under the hood when the `Blob` body is obtained.

I normally CC: @wanderview on this sort of thing, as he has a lot of expertise in Chrome's Cache Storage API implementation.

**Comment by wanderview** [comment] 2021-10-08 18:48
The Cache API only stores full responses and not partial responses.  I'm not sure how that interacts with the layers above.  I would probably need a reduced test case to investigate further.

**Comment by jeffposnick** [comment] 2021-10-08 18:56
A rough summary of the order of operations performed is:

```js
const response = await cache.match('video.mp4');
const blob = await response.blob();
const slicedBlob = originalBlob.slice(start, end);
const slicedResponse = new Response(slicedBlob, {
  status: 206,
  statusText: 'Partial Content',
  headers: response.headers,
});
// Set content-length and a few other headers, then pass slicedResponse to event.respondWith()
```

That's not the exact code, and I could simplify a reproduction beyond what's in https://service-worker-testing.vercel.app if needed. But perhaps that's enough to point to a possible root cause?

The  `await response.blob()` step of that process ends up throwing `TypeError: Failed to fetch`, apparently when that code sequence is called multiple times in quick succession due to multiple in flight `Range:` requests for the same video while scrubbing in the player.

**Comment by wanderview** [comment] 2021-10-08 19:30
Multiple responses with .blob() calls should not be a problem.  I guess if that could be reduced in a test case it would help.

One possible way to work around this, though, would be to cache the blob in a global variable in the service worker so you only have one per video.

**Comment by wanderview** [comment] 2021-10-08 19:33
How many overlapping requests are we talking about?  I guess its possible you could be running out of file descriptors or something.

**Comment by jeffposnick** [comment] 2021-10-08 20:11
> How many overlapping requests are we talking about? I guess its possible you could be running out of file descriptors or something.

Definitely not a lot. When I reproduced it using https://service-worker-testing.vercel.app there were maybe 2 or 3 requests that might have been in flight at once, so running out of file descriptors doesn't sound like it would be it.

I'll attempt to create a pared-down reproduction outside of Workbox in that case.

**Comment by wanderview** [comment] 2021-10-08 20:43
I see huge amounts of disk writes triggered by the vercel app.  I think maybe every blob slice is getting created as a separate blob and potentially flushed to disk separately.  Can you file a crbug?

**Comment by wanderview** [comment] 2021-10-08 20:51
I guess the only way to avoid this would be to return the full 200 response from the service worker to the video player.  I think that generally works with most video players, but not sure.

**Comment by jeffposnick** [comment] 2021-10-08 22:01
I've created https://bugs.chromium.org/p/chromium/issues/detail?id=1258212 to track the potential Chrome issue.

**Comment by jeffposnick** [comment] 2021-10-11 22:51
Based on the latest at https://bugs.chromium.org/p/chromium/issues/detail?id=1258212, it sounds like this will be addressed in a future release of Chrome, and there's not anything to track here.

**Closed as completed by jeffposnick** 2021-10-11 22:51 UTC
Labels: Bug, workbox-range-requests, Browser Compatibility

**Comment by jeffposnick** [comment] 2021-10-12 12:53
Based on the Chromium issue tracker thread, if you need a workaround in Chrome right away, you can avoid the buggy behavior by ensuring that the cache key and request URL don't match. (This bypasses the problematic optimization that Chrome attempts when there's a match.)

If you wanted to do that in Workbox, using a custom `cacheKeyWillBeUsed` plugin makes that pretty straightforward. Just be warned that if you do this, and if you ever remove the plugin, you should also delete the previously cached videos with the modified cache key.

Something like the following should work:

```js
import {registerRoute} from 'workbox-routing';
import {CacheFirst} from 'workbox-strategies';
import {RangeRequestsPlugin} from 'workbox-range-requests';

async function cacheKeyWillBeUsed({request}) {
  return request.url + '-bugfix';
};

registerRoute(
  ({url}) => url.pathname.endsWith('.mp4'),
  new CacheFirst({
    cacheName: 'bugfix-videos',
    plugins: [
      {cacheKeyWillBeUsed},
      new RangeRequestsPlugin(),
    ],
  }),
);
```

**Comment by jeffposnick** [comment] 2021-10-14 14:27
Hello @CryogenicPlanet—as per https://bugs.chromium.org/p/chromium/issues/detail?id=1258212#c13, @wanderview is having some trouble determining whether or not the changes made to Chrome have resolved the issue.

It looks like that's due to the original `fetchEvent.request` not being passed in to `cache.match()`.

Based on what I could tell from the sample code you provided, which uses the `CacheFirst` Workbox strategy, the `fetchEvent.request` should eventually be passed through to `cache.match()`. When I look at your current live deployment at https://service-worker-testing.vercel.app/, I see code that references a custom `FilesCacheFirst` strategy, but I'm having trouble tracing that back to what the underlying code is due to incomplete sourcemaps. It's not clear to me whether that custom strategy is causing a different value to be passed to `cache.match()`.

Are you able to restore the live demo to the original state, so that @wanderview can confirm the fix works as intended?

**Comment by wanderview** [comment] 2021-10-14 14:36
I have a further change that should fix the issue.  Its just waiting on review.

**Comment by wanderview** [comment] 2021-10-15 15:07
I believe the problem should be fixed in chrome canary 97.0.4670.0.

**Comment by CryogenicPlanet** [comment] 2021-10-15 20:46
Sorry for the delay, but I have updated the domain to the original state.

That said `FilesCacheFirst` in this test just wrapped around `CacheFirst` and didn't do much, we removed its functionality for this bug repo but I guess we pushed some wrong code up my mistake.

Will ask someone on our team to check that it works on the canary build, unfortunately I don't think there are canary builds for linux so I won't be able to check myself

**Comment by freosc** [comment] 2022-10-24 11:49
Sorry to bring this one back. I'm working on a not upgradable device (using an Android 8.0.0 webview, Chrome 92), and since I had the same error on a 200MB+ video file, I guess I have to use the workaround.
Only, when using the plugin you provided (simple implementation of cacheKeyWillBeUsed), the result is that the file is downloaded every time, instead of being served by the service worker. Not sure if that's the intention, but I guess not.

When adding the video to the cache in the first place, do I also need to use the key?
I add the video using cache.add(url), but I have no option there to change the key (I think)
