### ISSUE TITLE
Issue: dependency could not be resolved

### ISSUE THREAD

**Issue by McMomo** [GoogleChrome/workbox#2503] opened 2020-05-08 09:43 UTC
**Library Affected**:
*workbox-webpack-plugin.*

**Issue or Feature Request Description**:
In developement build, with workbox-webpack-plugin version 5.0.0 and upwards, i get the following log in the console. 

```
'workbox-core/registerQuotaErrorCallback.js' is imported by node_modules/workbox-expiration/ExpirationPlugin.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/assert.js' is imported by node_modules/workbox-routing/NavigationRoute.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/assert.js' is imported by node_modules/workbox-expiration/ExpirationPlugin.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/assert.js' is imported by node_modules/workbox-strategies/NetworkFirst.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/assert.js' is imported by node_modules/workbox-strategies/StaleWhileRevalidate.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/workbox-routing/NavigationRoute.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/workbox-routing/registerRoute.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/workbox-expiration/ExpirationPlugin.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/workbox-strategies/NetworkFirst.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/workbox-strategies/StaleWhileRevalidate.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/workbox-navigation-preload/enable.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/workbox-precaching/cleanupOutdatedCaches.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/WorkboxError.js' is imported by node_modules/workbox-routing/registerRoute.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/WorkboxError.js' is imported by node_modules/workbox-expiration/ExpirationPlugin.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/WorkboxError.js' is imported by node_modules/workbox-strategies/NetworkFirst.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/WorkboxError.js' is imported by node_modules/workbox-strategies/StaleWhileRevalidate.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/cacheNames.js' is imported by node_modules/workbox-expiration/ExpirationPlugin.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/cacheNames.js' is imported by node_modules/workbox-strategies/NetworkFirst.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/cacheNames.js' is imported by node_modules/workbox-strategies/StaleWhileRevalidate.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/cacheNames.js' is imported by node_modules/workbox-precaching/cleanupOutdatedCaches.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/dontWaitFor.js' is imported by node_modules/workbox-expiration/ExpirationPlugin.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/getFriendlyURL.js' is imported by node_modules/workbox-expiration/ExpirationPlugin.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/getFriendlyURL.js' is imported by node_modules/workbox-strategies/NetworkFirst.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/getFriendlyURL.js' is imported by node_modules/workbox-strategies/StaleWhileRevalidate.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/cacheWrapper.js' is imported by node_modules/workbox-strategies/NetworkFirst.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/cacheWrapper.js' is imported by node_modules/workbox-strategies/StaleWhileRevalidate.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/fetchWrapper.js' is imported by node_modules/workbox-strategies/NetworkFirst.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/fetchWrapper.js' is imported by node_modules/workbox-strategies/StaleWhileRevalidate.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/assert.js' is imported by node_modules/workbox-routing/Route.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/assert.js' is imported by node_modules/workbox-routing/RegExpRoute.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/workbox-routing/RegExpRoute.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/assert.js' is imported by node_modules/workbox-expiration/CacheExpiration.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/dontWaitFor.js' is imported by node_modules/workbox-expiration/CacheExpiration.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/workbox-expiration/CacheExpiration.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/WorkboxError.js' is imported by node_modules/workbox-expiration/CacheExpiration.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/workbox-precaching/precache.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/workbox-strategies/utils/messages.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/getFriendlyURL.js' is imported by node_modules/workbox-strategies/utils/messages.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/assert.js' is imported by node_modules/workbox-routing/utils/normalizeHandler.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/assert.js' is imported by node_modules/workbox-routing/Router.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/workbox-routing/Router.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/WorkboxError.js' is imported by node_modules/workbox-routing/Router.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/getFriendlyURL.js' is imported by node_modules/workbox-routing/Router.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/cacheNames.js' is imported by node_modules/workbox-precaching/utils/addFetchListener.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/getFriendlyURL.js' is imported by node_modules/workbox-precaching/utils/addFetchListener.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/workbox-precaching/utils/addFetchListener.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/assert.js' is imported by node_modules/workbox-precaching/PrecacheController.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/cacheNames.js' is imported by node_modules/workbox-precaching/PrecacheController.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/cacheWrapper.js' is imported by node_modules/workbox-precaching/PrecacheController.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/fetchWrapper.js' is imported by node_modules/workbox-precaching/PrecacheController.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/workbox-precaching/PrecacheController.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/WorkboxError.js' is imported by node_modules/workbox-precaching/PrecacheController.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/DBWrapper.js' is imported by node_modules/workbox-expiration/models/CacheTimestampsModel.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/deleteDatabase.js' is imported by node_modules/workbox-expiration/models/CacheTimestampsModel.js, but could not be resolved – treating it as an external dependency
'workbox-core/copyResponse.js' is imported by node_modules/workbox-precaching/PrecacheController.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/WorkboxError.js' is imported by node_modules/workbox-precaching/utils/createCacheKey.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/workbox-precaching/utils/printCleanupDetails.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/workbox-precaching/utils/printInstallDetails.js, but could not be resolved – treating it as an external dependency
```

**Comment by jeffposnick** [comment] 2020-05-08 15:26
Hmm... I just checked with a fresh `npm install workbox-webpack-plugin` in a clean directory, and `node_modules/workbox-core` ended up installed as one of its dependencies. It's strange that your local `webpack` doesn't think that any of the `workbox-core` modules exist.

Can you try removing your projects current `node_modules/` directory and doing a fresh `npm install` and see if that clears things up?

**Comment by McMomo** [comment] 2020-05-11 07:26
Unfortunately, the bug has not been fixed, but i saw some of my other dependencies use some deprecated dependencies. Is it possible that they cause this error?

**Comment by jeffposnick** [comment] 2020-05-11 13:56
All of those failure messages are related to `webpack` not being able to resolve the `workbox-core` module, which is a failure that I'm not able to reproduce. I am not sure what other deprecated dependencies you might be using, but I do think that this failure is related to _something_ about your `webpack` build environment, as if this issue were widespread, I think we would have heard from more developers at this point.

I'm happy to keep this open to see if anyone else reports a similar failure, but I'd recommend trying to pare down your `webpack` configuration to just the basics, and then re-add additional options until you find out what might be breaking things.

**Comment by McMomo** [comment] 2020-05-14 15:18
I pared my webpack configs down, but the messages still appeare when i use GenerateSW. Even without options. The messages don't appeare if i use InjectManifest from the same package.

**Comment by jeffposnick** [comment] 2020-05-14 16:24
I'm sorry to hear that this is still a problem.

Is your current minimal setup checked in to a public GitHub repo? If so, could you pass along the URL so that I could try to reproduce what you're seeing?

**Comment by McMomo** [comment] 2020-05-15 08:59
The problem occures only on the dev build and not in production, so not that bad.

No, sorry the repo is private.

**Comment by jeffposnick** [comment] 2020-06-01 16:12
I'm sorry, but I'm not able to reproduce and I have not heard of others running into this problem. Without steps that you can provide for a reproduction, I don't think there's anything actionable at this point, so I'm going to close this.

We can revisit if you could provide a public reproduction.

**Closed as completed by jeffposnick** 2020-06-01 16:12 UTC
Labels: Needs More Info, workbox-webpack-plugin

**Comment by PravinJadavDeca** [comment] 2020-12-17 11:18
I am also getting the same error in next-pwa package. and I have tried to install fresh node modules but didn't work for me.

`'workbox-core/_private/WorkboxError.js' is imported by node_modules/next-pwa/node_modules/workbox-routing/registerRoute.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/WorkboxError.js' is imported by node_modules/next-pwa/node_modules/workbox-strategies/NetworkOnly.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/assert.js' is imported by node_modules/next-pwa/node_modules/workbox-strategies/NetworkOnly.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/next-pwa/node_modules/workbox-routing/registerRoute.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/next-pwa/node_modules/workbox-precaching/cleanupOutdatedCaches.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/next-pwa/node_modules/workbox-strategies/NetworkOnly.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/timeout.js' is imported by node_modules/next-pwa/node_modules/workbox-strategies/NetworkOnly.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/cacheNames.js' is imported by node_modules/next-pwa/node_modules/workbox-precaching/cleanupOutdatedCaches.js, but could not be resolved – treating it as an external dependency
'workbox-routing/registerRoute.js' is imported by node_modules/next-pwa/node_modules/workbox-precaching/addRoute.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/next-pwa/node_modules/workbox-routing/RegExpRoute.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/assert.js' is imported by node_modules/next-pwa/node_modules/workbox-routing/RegExpRoute.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/assert.js' is imported by node_modules/next-pwa/node_modules/workbox-routing/Route.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/cacheNames.js' is imported by node_modules/next-pwa/node_modules/workbox-strategies/Strategy.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/WorkboxError.js' is imported by node_modules/next-pwa/node_modules/workbox-strategies/Strategy.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/next-pwa/node_modules/workbox-strategies/Strategy.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/getFriendlyURL.js' is imported by node_modules/next-pwa/node_modules/workbox-strategies/Strategy.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/next-pwa/node_modules/workbox-strategies/utils/messages.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/getFriendlyURL.js' is imported by node_modules/next-pwa/node_modules/workbox-strategies/utils/messages.js, but could not be resolved – treating it as an external dependency
'workbox-routing/Route.js' is imported by node_modules/next-pwa/node_modules/workbox-precaching/PrecacheRoute.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/getFriendlyURL.js' is imported by node_modules/next-pwa/node_modules/workbox-precaching/PrecacheRoute.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/next-pwa/node_modules/workbox-precaching/PrecacheRoute.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/getFriendlyURL.js' is imported by node_modules/next-pwa/node_modules/workbox-strategies/StrategyHandler.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/assert.js' is imported by node_modules/next-pwa/node_modules/workbox-strategies/StrategyHandler.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/timeout.js' is imported by node_modules/next-pwa/node_modules/workbox-strategies/StrategyHandler.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/next-pwa/node_modules/workbox-strategies/StrategyHandler.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/WorkboxError.js' is imported by node_modules/next-pwa/node_modules/workbox-strategies/StrategyHandler.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/assert.js' is imported by node_modules/next-pwa/node_modules/workbox-routing/utils/normalizeHandler.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/next-pwa/node_modules/workbox-routing/Router.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/assert.js' is imported by node_modules/next-pwa/node_modules/workbox-routing/Router.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/cacheMatchIgnoreParams.js' is imported by node_modules/next-pwa/node_modules/workbox-strategies/StrategyHandler.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/executeQuotaErrorCallbacks.js' is imported by node_modules/next-pwa/node_modules/workbox-strategies/StrategyHandler.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/getFriendlyURL.js' is imported by node_modules/next-pwa/node_modules/workbox-routing/Router.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/WorkboxError.js' is imported by node_modules/next-pwa/node_modules/workbox-routing/Router.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/Deferred.js' is imported by node_modules/next-pwa/node_modules/workbox-strategies/StrategyHandler.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/assert.js' is imported by node_modules/next-pwa/node_modules/workbox-precaching/PrecacheController.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/cacheNames.js' is imported by node_modules/next-pwa/node_modules/workbox-precaching/PrecacheController.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/WorkboxError.js' is imported by node_modules/next-pwa/node_modules/workbox-precaching/PrecacheController.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/next-pwa/node_modules/workbox-precaching/PrecacheController.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/waitUntil.js' is imported by node_modules/next-pwa/node_modules/workbox-precaching/PrecacheController.js, but could not be resolved – treating it as an external dependency
'workbox-strategies/Strategy.js' is imported by node_modules/next-pwa/node_modules/workbox-precaching/PrecacheStrategy.js, but could not be resolved – treating it as an external dependency
'workbox-core/copyResponse.js' is imported by node_modules/next-pwa/node_modules/workbox-precaching/PrecacheStrategy.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/cacheNames.js' is imported by node_modules/next-pwa/node_modules/workbox-precaching/PrecacheStrategy.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/getFriendlyURL.js' is imported by node_modules/next-pwa/node_modules/workbox-precaching/PrecacheStrategy.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/WorkboxError.js' is imported by node_modules/next-pwa/node_modules/workbox-precaching/PrecacheStrategy.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/next-pwa/node_modules/workbox-precaching/PrecacheStrategy.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/WorkboxError.js' is imported by node_modules/next-pwa/node_modules/workbox-precaching/utils/createCacheKey.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/next-pwa/node_modules/workbox-precaching/utils/printCleanupDetails.js, but could not be resolved – treating it as an external dependency
'workbox-core/_private/logger.js' is imported by node_modules/next-pwa/node_modules/workbox-precaching/utils/printInstallDetails.js, but could not be resolved – treating it as an external dependency`
