### ISSUE TITLE
StaleWhileRevalidate do not make the second call to update the Service Worker

### ISSUE THREAD

**Issue by davidpaley** [GoogleChrome/workbox#2767] opened 2021-03-03 19:13 UTC
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*"all browsers".*

**Issue or Feature Request Description**:
I am using [Next Offline library](https://github.com/hanford/next-offline) for [this site](https://www.cityfurniture.com/product/6190100/havana-dark-gray-upholstered-side-chair-w-chrome-legs). I set this configuration:
```
workboxOpts: {
                  swDest: '../public/service-worker.js',
                  maximumFileSizeToCacheInBytes: 20000000,
                  runtimeCaching: [
                    {
                      urlPattern: /https:\/\/fonts\.googleapis\.com\/icon[\w\-_\/\.\:\?\=\&\+]*/,
                      handler: 'CacheFirst',
                      options: {
                        cacheName: 'google-fonts',
                        expiration: {
                          maxEntries: 10,
                          maxAgeSeconds: 30 * 24 * 60 * 60, // 1 month
                        },
                      },
                    },
                    {
                      urlPattern: /^((?!tracker).)*\.(jpeg|png|jpg|ico|svg)\??.*/,
                      handler: 'CacheFirst',
                      options: {
                        cacheName: 'img-cache',
                        expiration: {
                          maxEntries: 15,
                          maxAgeSeconds: 2 * 24 * 60 * 60, // 2 days
                        },
                      },
                    },
                    {
                      urlPattern: /https:\/\/embed.widencdn.net\/img\/cityfurniture.*.(jpeg|png|jpg)\?.*/,
                      handler: 'StaleWhileRevalidate',
                    },
                    {
                      urlPattern: /https:\/\/auth-cityfurniture.dotcmscloud.com\/(dA|contentAsset\/image)[\w\-_\/\.\:\?\=\&\+]*/,
                      handler: 'StaleWhileRevalidate',
                    },
                    {
                      urlPattern: /^((?!monetate).)*\.(js)$/,
                      handler: 'StaleWhileRevalidate',
                    },
                  ],
                },
```
As the js files are configured with the strategy Stale While Revalidate, when I went to the network tab in the Developers tools I was hoping to see two requests for the files cached in the Service Worker (SW), one for the SW request and one for the update of the data on the SW. But I am seeing just one request for the SW JS files. Am I understanding this wrong? It should do another call to revalidate the content of the SW, right?

**Comment by jeffposnick** [comment] 2021-03-04 18:58
I'm seeing the revalidation requests when I visit your site; are you sure that when you're testing things, the service worker is in [control of the page](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#scope_and_control)? Try navigating away after your first visit, and then returning. Alernatively, try setting `clientsClaim: true` if you want the newly registered service worker to take control of open tabs right away,

![Screen Shot 2021-03-04 at 1 55 48 PM](https://user-images.githubusercontent.com/1749548/110015213-9db85d00-7cf1-11eb-8c9d-bc06fc2040f4.png)

I'm going to close this and assume that's what the issue is, but if you're still seeing unexpected behavior, let us know and we can revisit.

**Comment by davidpaley** [comment] 2021-03-11 12:32
> I'm seeing the revalidation requests when I visit your site; are you sure that when you're testing things, the service worker is in [control of the page](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#scope_and_control)? Try navigating away after your first visit, and then returning. Alernatively, try setting `clientsClaim: true` if you want the newly registered service worker to take control of open tabs right away,
> 
> ![Screen Shot 2021-03-04 at 1 55 48 PM](https://user-images.githubusercontent.com/1749548/110015213-9db85d00-7cf1-11eb-8c9d-bc06fc2040f4.png)
> 
> I'm going to close this and assume that's what the issue is, but if you're still seeing unexpected behavior, let us know and we can revisit.

@jeffposnick It is working except for the files that comes from the same origin. For example, 
this is production: https://www.cityfurniture.com/browse/dining-room. If you check for the chunks, for example, at this moment: https://www.cityfurniture.com/_next/static/chunks/commons.98875a76810ab7396f70.js. I can only see the fetch of the service worker after the second reload. 
![image](https://user-images.githubusercontent.com/4527780/110787672-68a98e80-824c-11eb-89d7-004882864600.png)

Please, reload it at least 2 times. 

`navigator.serviceWorker.controller` show me that everything is ok 
![image](https://user-images.githubusercontent.com/4527780/110787781-8a0a7a80-824c-11eb-973f-3f6402b72298.png)

**Comment by jeffposnick** [comment] 2021-03-11 16:15
After investigating a bit more, the reason you're not seeing revalidation revalidation requests for those URLs is that they're precached, and therefore the runtime caching strategy doesn't apply to them. You can verify this by looking at the precache manifest in your service worker:

```
{
    url: "_next/static/chunks/commons.98875a76810ab7396f70.js",
    revision: "c81835a6270f5f4fdbd3aa185a230a52"
},
```

Precached URLs will be updated automatically "in the background" when the manifest information for them changes. They don't need to be revalidated at runtime,

**Closed as completed by jeffposnick** 2021-03-11 16:15 UTC

**Comment by jeffposnick** [comment] 2021-03-11 18:40
By the way, I wrote about the techniques I used when debugging this at https://jeffy.info/2021/03/11/debugging-sw-request.html

I hope that helps some other folks!

**Comment by davidpaley** [comment] 2021-03-12 18:34
Thank you so much @jeffposnick! You are totally right! And thank you for the blog post, really interesting :)
