### ISSUE TITLE
sw-offline-google-analytics cannot store all requests

### ISSUE THREAD

**Issue by ozgurky** [GoogleChrome/workbox#210] opened 2017-02-15 09:41 UTC
**Library Affected**:
*sw-offline-google-analytics*

**Browser & Platform**:
*all browsers.*

I am trying to use offline-analytics in an amp page and my page send several google analytics requests. when i inspect indexed db i see only one entry because other requests canceled. Is there a restriction using sw-offline in an amp (amp-project) page?

**Comment by jeffposnick** [comment] 2017-02-15 14:53
I can't say that I've previously used the offline analytics library on an AMP page, but at the same time, if you're seeing at least some requests queued up, it's likely that it should work.

Could you pass along a URL at which we could reproduce the issue?

**Comment by ozgurky** [comment] 2017-02-16 05:11
Thanks for reply. You can the implementation from this url.

https://m.mynet.com/

It is a full amp site with pwa support.

**Comment by ozgurky** [comment] 2017-02-21 09:09
As an extra info, only event (not pageview) requests queued up when network is offline.

**Comment by jeffposnick** [comment] 2017-02-21 20:25
Thanks for debugging that! CC: @prateekbh who is working on the next-generation of the offline analytics library, based on his https://github.com/GoogleChrome/sw-helpers/tree/master/packages/sw-background-sync-queue. It's something we should take into account in that version, too.

I think we can get out a new release of the existing codebase with your fix integrated with it, though it might have to wait a little bit. Our build and release process has changed significantly since the last `sw-offline-google-analytics` release.

**Comment by DjulLau** [comment] 2017-06-07 08:47
Hi,

I think there may be another problem : the key used to store the entry in IndexedDB is the URL as per
`return idbHelper.put(url.toString(), time || Date.now());`
When using measurement protocol (like in my case) same event may produce same URL thus replacing the previous entry instead of creating a new one (and that's the behaviour I witness when testing) or am I missing something ?

**Comment by gauntface** [comment] 2017-11-01 17:31
@philipwalton Is this covered in unit tests for V3? and If so can we close it now?

**Comment by philipwalton** [comment] 2017-11-01 17:43
I think the problem described by @DjulLau should be fixed, since we now use an object store with `autoIncrement:true` (so keys should always be unique).

The problem described by @ozgurky sounds like it might be a problem (if `/r/collect` is indeed a valid measurement protocol path).

I'll reach out to the team and confirm the total list of valid paths.

**Closed** 2017-12-01 01:14 UTC
Labels: bug, workbox-google-analytics
