### ISSUE TITLE
Precaching the generated WebpackPwaManifest manifest asset

### ISSUE THREAD

**Issue by niveditaece** [GoogleChrome/workbox#1588] opened 2018-07-26 13:02 UTC
*workbox-webpack-plugin.^3.4.1

**Browser & Platform**:
chrome,"webpack": "^4.15.0",node v10.6.0,npm 6.1.0,ubuntu 16.04

i wish to add generated manifest.json to the SWprecache array .
copied/generated manifest.json does not get included in precache-manifest.js.
This is the config i am using in webpack config:
new WebpackPwaManifest({
      name: 'TestApp',
      short_name: 'TestApp',
      description: 'Description!',
      background_color: '#01579b',
      theme_color: '#01579b',
      'theme-color': '#01579b',
      start_url: '/',
      icons: [
        {
          src: path.resolve('src/assets/icons/icon.png'),
          sizes: [96, 128,144,152,192, 256, 384, 512],
          destination: path.join('assets', 'icons')
        }
      ]
    }),
    new InjectManifest({
      globDirectory: '.',
  globPatterns: ['dist/manifest.*.json'],
      swSrc: './src/sw-default.js',
      swDest: './sw.js',
      
    })

Tried with new CopyWebpackPlugin([{from:'./src/manifest.json',**to:'./assets'**},{from:'./src/assets/icons',to:'assets/icons'}]),
manifest.json is precached.
but with 
new CopyWebpackPlugin([{from:'./src/manifest.json'},{from:'./src/assets/icons',to:'assets/icons'}]),
it does not work -InjectManifest plugin adds manifest.json if its in assets directory but not when its in the same build directory .

Is this an issue with the plugin or should i configure it differently?
-----------Edit: got manifest.json in to precache by providing the glob directory  as src and patterns as .json. But i had to generate manifest.json in the source directory to get it in to precache manifest. Please let me know if this can be achieved through plugin .

**Comment by jeffposnick** [comment] 2018-07-26 20:07
I'm thinking that we might need to do something specific to pick up on the output of the `WebpackPwaManifest` in the list of assets that `workbox-webpack-plugin` knows about.

**Comment by ivnmaksimovic** [comment] 2018-09-07 15:36
It's a default config, not a bug? Took me a lot of time until I found this answer https://stackoverflow.com/a/52112483/2722212

Apparently `exclude` option excludes manifest by default with default value of `[/\.map$/, /^manifest.*\.js(?:on)?$/]`

Why is excluding manifest.json a reasonable default?

**Comment by pe-wu** [comment] 2018-11-15 18:31
It's fixed in v4.0.0-alpha.0 ([#1679](https://github.com/GoogleChrome/workbox/pull/1679))

**Closed** 2019-02-19 21:40 UTC
Labels: Bug, P2, workbox-webpack-plugin
