### ISSUE TITLE
Add deleteCacheAndMetadata() recipe to docs

### ISSUE THREAD

**Issue by adityapunjani** [GoogleChrome/workbox#2234] opened 2019-09-24 20:39 UTC
**Library Affected**:
workbox.expiration.Plugin / workbox-runtime-caching

**Browser & Platform**:
all browsers.

**Feature Request Description**:
Currently, we don't have a method which can delete all the entries and metadata from IDB and cacheAPI for a given `cacheName`. A common use case with workbox runtime caching deployments at scale is to delete cache entries namespaced by a `cacheName` + `version`. This requirement stems from basic versioning of caches, passed to runtime strategies, and when a cache version is bumped we want to clean up previous version's cache & IDB entries, usually in the `activate` event of the SW. 

This is easily possible to do for CacheAPI entries but hard to work with IDB where the implementation is tightly coupled to Workbox. I'd love to hear thoughts on  `deleteCacheAndMetadata` API to accept an optional `cacheName` parameter that would purge only the CacheAPI and IDB entries for that specific cache name. 

Proposed API `deleteCacheAndMetadata(cacheName)` 

Implementation: This should be fairly straightforward to implement for CacheAPI entries. For IDB we are currently using an IDBKeyRange such as ``IDBKeyRange.bound(cacheName, `${cacheName}\uffff`);`` to delete IDB entries manually outside of workbox.

**Comment by philipwalton** [comment] 2019-09-25 01:40
Though perhaps not the most user-friendly API, you _can_ do what you want today by creating a new `CacheExpiration` instance with `maxEntries` set to 0.

Something like this should work:

```js
import {CacheExpiration} from 'workbox-expiration/CacheExpiration';

addEventListener('activate', (event) => {
  event.waitUntil(
    new CacheExpiration('my-cache:v1', {maxEntries: 0}).expireEntries(),
  )
});
```

We could potentially create a convenience method that does something like this; however, after thinking about it a bit, requiring that the developer know the cache name may not be the best API.

Rather than asking them to remove metadata for a particular cache name, I think it might make more sense to have a method that clears all metadata for entries not in a specific whitelist of caches. We could even default to removing everything not in the list of currently used caches (e.g. `await caches.keys()`)

That would allow you to easily clear unused entries for a user who may be upgrading from a _really_ old version of the service worker.

What do you think?

**Comment by adityapunjani** [comment] 2019-09-25 04:51
> Though perhaps not the most user-friendly API, you can do what you want today by creating a new CacheExpiration instance with maxEntries set to 0.

Hah! That's really clever. Thanks for sharing. I'll try it out. 

> Rather than asking them to remove metadata for a particular cache name, I think it might make more sense to have a method that clears all metadata for entries not in a specific whitelist of caches. 

This makes a-lot of of sense to me. It is similar to what most folks do in the `activate` event for the CacheAPI entries. I agree it's better for workbox to abstract away the cacheNames as in the dev land we are not really aware about workbox's internal cache names, but to your point the API should accept a whitelist of cacheNames which is controlled directly by the developers.

**Comment by jeffposnick** [comment] 2019-09-25 13:06
Hey @adityapunjani—I'm a little confused; there's [already a `deleteCacheAndMetadata()` method](https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.expiration.Plugin.html#deleteCacheAndMetadata) exposed by the `ExpirationPlugin` class, which will perform the deletion/cleanup for the cache(s) + IDB object store(s) associated with a given `ExpirationPlugin` instance. (A single `ExpirationPlugin` could be associated with multiple caches.)

Are you saying that the method is unsuitable for your use case, and that you need a different, static version takes in a `cacheName` as a parameter?

If you do need that functionality for an arbitrary `cacheName`, you could implement it directly via:

```
import {CacheExpiration} from 'workbox-expiration';

async function deleteCacheAndMetadata(cacheName) {
  await caches.delete(cacheName);
  const cacheExpiration = new CacheExpiration(cacheName);
  cacheExpiration.delete();
}
```

Given that straightforward implementation, how important would it be to take that static function and officially make it part of the Workbox public interface?

**Comment by philipwalton** [comment] 2019-09-25 13:15
> there's [already a `deleteCacheAndMetadata()` method](https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.expiration.Plugin.html#deleteCacheAndMetadata) exposed by the `ExpirationPlugin` class

Hmmm, I guess I missed that method.

However, I still do think for most real service worker-upgrade use cases, a developer can't assume anything about the previous versions a user may have installed, and it's best to just clear everything except entries for a known set of current caches. I think a convenience method to do that might make sense.

**Comment by jeffposnick** [comment] 2019-09-25 15:19
> However, I still do think for most real service worker-upgrade use cases, a developer can't assume anything about the previous versions a user may have installed, and it's best to just clear everything except entries for a known set of current caches.

IndexedDB and Cache Storage are shared across a single origin, and multiple service workers that "don't know about each other" might be registered for that origin. If you're sure that you're deploying the only service worker for a given origin, and you know that you have a tight coupling between service worker logic and runtime caches, I could see a helper method potentially being useful—but only if those conditions are met.

(I am not convinced that using runtime caches that are tightly coupled with a service worker version is a _common_ practice. In my experience, runtime caches are more likely to be used for API responses, images, or other dynamically fetched data. While there are versioning considerations for this type of data, those considerations are often decoupled from the service worker logic.)

Anyway, here's how you could accomplish what you describe, using the existing public Workbox API. We could wrap that in a helper method... somewhere? (`workbox-core`?) if there's sufficient demand.

```
async function cleanupAllCachesExcept(cachesToKeep) {
  const allCaches = await caches.keys();
  const cachesToCleanup = allCaches.filter((cache) => !cachesToKeep.includes(cache));
  for (const cacheToCleanup of cachesToCleanup) {
    await deleteCacheAndMetadata(cacheToCleanup);
  }
}

async function deleteCacheAndMetadata(cacheName) {
  await caches.delete(cacheName);
  const cacheExpiration = new CacheExpiration(cacheName);
  cacheExpiration.delete();
}
```

**Comment by jeffposnick** [comment] 2019-09-25 15:58
...and just to be explicit about why I'm posting examples of accomplishing the desired behavior, we've historically been reluctant to add in code that isn't likely to get wide use into an official package, unless it's impossible to accomplish it using the existing API.

Instead, we've added these types of recipes [to our docs](https://developers.google.com/web/tools/workbox/guides/advanced-recipes) for folks to use in their own service workers if they need them.

Perhaps with the move towards fine-grained exports and build-your-own-bundles in v5, minimizing the code in the official packages is less important. There still are likely to be a good number of CDN users with v5, though, so I think we should still keep our packages lean until (if?) we deprecate the CDN at some point in the future.

**Comment by adityapunjani** [comment] 2019-09-25 17:46
> Hey @adityapunjani—I'm a little confused; there's already a deleteCacheAndMetadata() method exposed by the ExpirationPlugin class, which will perform the deletion/cleanup for the cache(s)

Yeah the use cases in my mind were was specific to managing individual cache lifecycles through versioning. A simple real world example is, we add a WB ServiceWorker that adds runtime caching for API responses, images, fonts etc. Later we decided to remove the runtime caching for just images. What would be the best practice to clean up the `image_cache` IDB entries in the next SW upgrade? 

I've seen similar questions asked on StackOverflow before Ex. https://stackoverflow.com/questions/48499635/workbox-cache-versioning-best-practice

I think using `CacheExpiration` to achieve should works. It just din't come to mind intuitively. The only tricky bit here would be to not accidentally clear workbox managed caches.

**Comment by jeffposnick** [comment] 2019-09-25 17:56
> I think using `CacheExpiration` to achieve should work. It just din't come to mind intuitively. The only tricky bit here would be to not accidentally clear workbox managed caches.

Great. If we added that `deleteCacheAndMetadata()` function to the recipes docs, would you consider this issue closed?

**Comment by adityapunjani** [comment] 2019-09-25 17:59
@jeffposnick Yeah that sounds good to me! Thanks.

**Comment by philipwalton** [comment] 2019-09-26 01:05
@jeffposnick I still think there's a use case that the current API doesn't solve, and I think it's actually more important than deleting entries for an individual cache name.

Consider this example:

1. An app creates an initial runtime cache.
2. Laster, the app decides to split that into two separate caches for images and API requests with separate expiration rules.
3. Later still, the app decides to change one of the API endpoint URLs
4. Finally, the app moves their images to a new CDN so all URLs will change

In all of the above update cases, one or more new cache names may be in order, but I don't think it's a good idea for the app's `activate` event to individually list all old cache names that need to be removed.

Instead, the app would want to say: _remove all entries from the `workbox-cache-expiration` object store that don't match the following, currently-used cache names._

With the current API, you can only expire entires that match a particular name. You can't expire entires that *don't* match a name (or a list of names).

**Comment by jeffposnick** [comment] 2019-09-26 01:49
> With the current API, you can only expire entires that match a particular name. You can't expire entires that don't match a name (or a list of names).

Apologies if I'm missing some nuance, but isn't that what happens in that `cleanupAllCachesExcept()` recipe?

**Comment by philipwalton** [comment] 2019-09-26 01:57
> Apologies if I'm missing some nuance, but isn't that what happens in that `cleanupAllCachesExcept(cachesToKeep)` recipe?

If a developer has manually deleted caches in the past without clearing the entries from the `workbox-expriation` object store, then it would be different.

Specifically, consider these lines in your code above:

```js
const allCaches = await caches.keys();
const cachesToCleanup = allCaches.filter((cache) => !cachesToKeep.includes(cache));
```

In this code, `cachesToCleanup` would necessarily be a subset of `allCaches`, but in the case I'm describing there could be entries in the `workbox-expriation` object store for old caches that would not be returned by `caches.keys()`.

**Comment by jeffposnick** [comment] 2019-09-26 14:11
> Not in all cases. If a developer has manually deleted caches in the past without clearing the entries from the workbox-expriation object store, then it would be different.

If we're putting out guidance, both "use this `deleteCacheAndMetadata(cacheName)` recipe instead of `caches.delete(cacheName)` iff you're using cache expiration" and "inside your `activate` handler, delete all caches + IDB metadata that aren't in a whitelist" are possible options. (I'd personally prefer going with the first approach, especially since multiple SWs can share the same origin storage.)

If there are lightweight methods missing from our IDB-related code that make it impossible to accomplish what you'd want, then I'm supportive of those being added, and then showing how to use them as part of a recipe.

**Comment by adityapunjani** [comment] 2019-09-26 17:41
I agree with @philipwalton that IDB entries and cache API can get out of sync. I've seen this happen first hand in the past.

**Comment by mmazzarolo** [comment] 2020-05-01 10:00
> > However, I still do think for most real service worker-upgrade use cases, a developer can't assume anything about the previous versions a user may have installed, and it's best to just clear everything except entries for a known set of current caches.
> 
> IndexedDB and Cache Storage are shared across a single origin, and multiple service workers that "don't know about each other" might be registered for that origin. If you're sure that you're deploying the only service worker for a given origin, and you know that you have a tight coupling between service worker logic and runtime caches, I could see a helper method potentially being useful—but only if those conditions are met.
> 
> (I am not convinced that using runtime caches that are tightly coupled with a service worker version is a _common_ practice. In my experience, runtime caches are more likely to be used for API responses, images, or other dynamically fetched data. While there are versioning considerations for this type of data, those considerations are often decoupled from the service worker logic.)
> 
> Anyway, here's how you could accomplish what you describe, using the existing public Workbox API. We could wrap that in a helper method... somewhere? (`workbox-core`?) if there's sufficient demand.
> 
> ```js
> async function cleanupAllCachesExcept(cachesToKeep) {
>   // Keep the caches that Workbox uses internally.
>   cachesToKeep.push(
>       cacheNames.precache, cacheNames.runtime, cacheNames.googleAnalytics);
>   const allCaches = await caches.keys();
>   const cachesToCleanup = allCaches.filter((cache) => !cachesToKeep.includes(cache));
>   for (const cacheToCleanup of cachesToCleanup) {
>     await deleteCacheAndMetadata(cacheToCleanup);
>   }
> }
> 
> async function deleteCacheAndMetadata(cacheName) {
>   await caches.delete(cacheName);
>   const cacheExpiration = new CacheExpiration(cacheName);
>   cacheExpiration.delete();
> }
> ```

Please notice that as of today (`"workbox-expiration": "5.1.3"`) initializing a new CacheExpiration plugin without a configuration like done in the snippet throws: 
```
Uncaught WorkboxError: You must define either config.maxEntries or config.maxAgeSecondsin workbox-cache-expiration.Plugin.constructor.
```
  
Setting a config with `maxEntries: 0` or `maxAgeSeconds: 0` won't work either, because [this line of code](https://github.com/GoogleChrome/workbox/blob/234e69d9506be9301705171ba0dbfe046262f029/packages/workbox-expiration/src/ExpirationPlugin.ts#L60) is doing a truthy check (not sure if it's by design or not).  

As a workaround, setting a config to `maxEntries: 1` seems to be working fine for me.

**Comment by tomayac** [comment] 2024-04-25 08:57
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team

**Closed by tomayac** 2024-04-25 08:57 UTC
Labels: Documentation, workbox-expiration
