### ISSUE TITLE
Precaching is in a bad state following a failed activation in Firefox

### ISSUE THREAD

**Issue by rolandstarke** [GoogleChrome/workbox#1783] opened 2018-12-09 01:03 UTC
**Library Affected**:
*workbox-v3.6.3*

**Browser & Platform**:
Firefox 63.0.3 Windows

**Issue or Feature Request Description**:
Basically the same as https://github.com/GoogleChrome/workbox/issues/1528, but it would be cool if the problem would be solved in the library itself.

I am using the InjectManifest plugin (its the same with GenerateSW). 

After a deploy the service woker claims to have updates. When closing the browser and opening it again one js file is deleted form the cache. The index.html is still on the old version that depends on this js file. So the page can't load anymore.

Here the config (i am using https://www.npmjs.com/package/@vue/cli-plugin-pwa)

vue.config.js
```
process.env.VUE_APP_VERSION = (new Date()).toISOString();

module.exports = {
    devServer: {
        proxy: 'http://localhost:8000'
    },
    // ...other vue-cli plugin options...
    pwa: {
        name: 'My App',
        themeColor: '#4DBA87',
        msTileColor: '#000000',
        appleMobileWebAppCapable: 'yes',
        appleMobileWebAppStatusBarStyle: 'black',
        workboxPluginMode: 'InjectManifest',
        workboxOptions: {
            //https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin
            swSrc: __dirname + '/public/service-worker.js',
            dontCacheBustUrlsMatching: /\.[0-9a-f]{8}\./,
            importWorkboxFrom: 'local',
        }
    }
}
```
__dirname + '/public/service-worker.js'
```
workbox.setConfig({
    debug: true
});
workbox.core.setLogLevel(workbox.core.LOG_LEVELS.debug);


workbox.core.setCacheNameDetails({prefix: "my-garden"});

/**
 * The workboxSW.precacheAndRoute() method efficiently caches and responds to
 * requests for URLs in the manifest.
 * See https://goo.gl/S9QRab
 */
self.__precacheManifest = [].concat(self.__precacheManifest || []);
//workbox.precaching.suppressWarnings();
workbox.precaching.precacheAndRoute(self.__precacheManifest, {});

workbox.routing.registerNavigationRoute("/index.html", {
  
  blacklist: [/^\/(api|admin|vendor|storage)/,/\.[a-z]{2,5}$/i],
});
```

The server is configured to not serve 404, but to fallback to index.html instead.

**Comment by jeffposnick** [comment] 2018-12-11 22:22
Thanks for the very detailed writeup; I'll try to reproduce the issue locally.

One question for you: you mentioned that you're seeing this in Firefox 63. Can you also reproduce that behavior in other browsers, like Chrome?

That message in this screenshot about the service worker attempting to pull in what I'd imagine is the old precache manifest via `importScripts()`, and getting back the `text/html` fallback response instead, definitely look suspicious. A theory that I have has to do with Firefox being more aggressive about checking for updates to resources pulled in to the SW scope via `importScripts()` vs. how Chrome behaves at the moment. That might lead to it entering into a state where it has an inaccurate precache manifest right after an update. So a quick check to see if Chrome is doing the same thing would be 👍

**Comment by rolandstarke** [comment] 2018-12-11 23:31
Hey, yes you are right thats the old precache manifest and the fallback response from the server. Chrome, as far as i know, did not retry to load the old manifest and cached it. (or maybe its not shown in the console) For Firefox I also checked the access.log and saw that in the state where updates are available but clients are not claimed yet that both precache manifests are requested.

Maybe the precache manifest file could be included in itself to overcome this issue. For now i just set a public max age 1 year cache header for this file to overcome this error.

....


The main issue is still there. I could not reproduce it in chrome.



I made some side by side images On the left Firefox on the right chrome. (btw in Firefox its reproducible like 80% of the times.)

1. active service worker, everything is cached and works normal
![1](https://user-images.githubusercontent.com/5196813/49836526-3a098880-fda3-11e8-8e01-c97db0f85b20.png)

2. deploy (in this case i just rebuild the app, there is a timestamp of the buildtime in the app, that is rendered in the frontent, so dist/js/app.{hash}.js and dist/js/index.html always change.)

![2](https://user-images.githubusercontent.com/5196813/49836671-d0d64500-fda3-11e8-8a96-8849d55f001d.png)

3. reload the page
![3](https://user-images.githubusercontent.com/5196813/49836691-dd5a9d80-fda3-11e8-86f7-d3bec373f39a.png)

4. reload the page again (not sure if necessary, but in my first attempt to reproduce it a single reload did not result in a broken app)
![4](https://user-images.githubusercontent.com/5196813/49836744-1abf2b00-fda4-11e8-876f-ef39bef2b042.png)

5. close tabs
![5](https://user-images.githubusercontent.com/5196813/49836868-9c16bd80-fda4-11e8-99a9-8a28a9e51828.png)

6. open page again
![6](https://user-images.githubusercontent.com/5196813/49836792-42ae8e80-fda4-11e8-9d85-de9424de0c4d.png)

7. reload  page (in Firefox the site is now broken)
![7](https://user-images.githubusercontent.com/5196813/49836830-738ec380-fda4-11e8-846e-6d8ccfcc01db.png)

**Comment by jeffposnick** [comment] 2018-12-12 22:10
(CC: @josephliccini who brought up what looks to be the root cause in https://github.com/w3c/ServiceWorker/issues/1372, and @wanderview whom I've been bugging about this as an FYI.)

Thanks again for all those debugging steps. I think I have a decent handle on what you're seeing in Firefox.

Based on [this screenshot](https://user-images.githubusercontent.com/5196813/49836792-42ae8e80-fda4-11e8-9d85-de9424de0c4d.png), what looks like is happening is that the `activate` event is fired on the `waiting` service worker, during which all of the `Response` objects that were in Workbox's temporary cache are supposed to be moved over to the activate cache. However, "something" happens in Firefox that causes that activation to fail. I believe those 3 blank "Error" log messages you can see at the top of the screenshot correspond to this activation failure. (I have no idea what's causing this failure, as it appears to be internal to Firefox—a `catch()` at the end of the promise passed to `event.waitUntil()` during activation doesn't get triggered.)

So, for whatever reason, the `activate` handler does not fully complete, and as per https://github.com/w3c/ServiceWorker/issues/1372#issue-387063936, in Firefox, the worker is discarded and a new `install` event is fired. That's why you see a message about precaching starting over again after those blank "Error" log messages.

The problem here is that the first thing the `install` handler does is clear out the temporary cache: https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-precaching/controllers/PrecacheController.mjs#L167-L177

Workbox does not expect to be in a state where there's anything useful in the temporary cache at this point; it expects that if there's a new `install` event, it can start fresh with the current set of assets in the precache manifest.

...but for reasons that have to do with how we keep track of revision information in IndexedDB, that assumption will lead to the behavior you're seeing in Firefox if we get an unexpected `install` event following an incomplete `activate` event.

I believe that the workaround is Workbox just *not* to delete the temporary cache at the start of the `install` handler, and assume that if there's anything left over in it, it should actually be copied over during the next successful `activate` event (at which point it will be cleaned up).

As far as I can tell, that's a low-risk change, but it's likely something we'd make against the `next` branch and give folks a chance to test in the next v4 beta release.

**Comment by jeffposnick** [comment] 2018-12-13 20:41
It might not be the best bug report in the world, but I tried to capture the steps that led to Firefox failing to activate the updated service worker at https://bugzilla.mozilla.org/show_bug.cgi?id=1514030

We still want to address this from a Workbox perspective, but at the same time, if Firefox appears to get into a bad state where it fails to activate a new service worker, that's hopefully something that can be resolved too.

**Comment by jeffposnick** [comment] 2019-02-20 21:04
This is addressed in Workbox v4, where the only thing `workbox-precaching` performs in the `activate` handler is cleanup.

**Closed by jeffposnick** 2019-02-20 21:04 UTC
Labels: Browser Compatibility, Bug, workbox-precaching
