### ISSUE TITLE
workbox-webpack-plugin doesn't add an entry in the array for my index.html

### ISSUE THREAD

**Issue by Richienb** [GoogleChrome/workbox#1692] opened 2018-10-10 09:07 UTC
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*irrelevant*

**Issue or Feature Request Description**:
When I use workbox-webpack-plugin's injectmanifest command in Webpack 3 and inspect the generated file, the output looks something like this:
```js
self.__precacheManifest = [
  {
    "revision": "c6de43433d90181622aa",
    "url": "bundle.js"
  },
  {
    "revision": "33299ea0bd8e99ac4c4def3e01ee859a",
    "url": "bundle.css"
  }
];
```
The problem is that webpack doesn't cache my index.html despite being specified in the `webpack.config.js` file.

**Reproduction steps**:
*Step 1: Cloning*

The source code is [here on GitHub](https://github.com/Richienb/richienb.github.io/tree/89bf8314fee14a8f994915d26db3a80b6df0589a) but you can reproduce it locally by running:

```sh
git clone https://github.com/Richienb/richienb.github.io.git
git checkout 89bf8314fee14a8f994915d26db3a80b6df0589a .
```

*Step 2: Navigate to directory*

Fairly simple:
```sh
cd richienb.github.io
cd src
```

*Step 3: Installation*

This repository uses yarn so for this step, install yarn then install all the packages in a development environment

```sh
npm install -g yarn
yarn install --production false
```

*Step 4: Locally host the site*

In this step, tell webpack-dev-server to host a local server of the site

```sh
npm start
```

*Step 5: Find the generated file*

Inspect the command line output and find the file starting with `precache-manifest`. An example is pointed out below:

```
Project is running at http://localhost:8080/
webpack output is served from /
Hash: 47d2479a673bec7d5643
Version: webpack 3.12.0
Time: 34762ms
                                                Asset       Size  Chunks             Chunk Names
                                           bundle.css     118 kB          [emitted]
                                            bundle.js     245 kB       0  [emitted]  main
precache-manifest.15dc3d014eed9db2538054395c7d9c0b.js  186 bytes          [emitted]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                    service-worker.js       1 kB          [emitted]
   [7] ./node_modules/@material/ripple/index.js 20.2 kB {0} [built]
```

*Step 6: Navigate to the site*

Navigate to the generated file. For the example above, you would navigate to `127.0.0.1/precache-manifest.15dc3d014eed9db2538054395c7d9c0b.js`.

*Step 7: View the resulting file*

The file will look similar to this:

```js
self.__precacheManifest = [
  {
    "revision": "c6de43433d90181622aa",
    "url": "bundle.js"
  },
  {
    "revision": "33299ea0bd8e99ac4c4def3e01ee859a",
    "url": "bundle.css"
  }
];
```

As you can see, an entry for `index.html` clearly does not exist but in the `webpack.config.js` it is clearly declared. That is the problem.

**Comment by SamStonehouse** [comment] 2018-10-22 14:14
I've resolved my issue, it was to do with the ordering of webpack plugins, it seems the Workbox plugin must be last for it to pick up on some files. Hope this helps with your issue.

**Comment by jadjoubran** [comment] 2018-11-16 16:03
Hey @Richienb 
can you please show your webpack configuration?

**Comment by Richienb** [comment] 2018-11-16 19:10
All of the code including the Webpack configuration was given in the original comment

**Comment by jadjoubran** [comment] 2018-11-16 20:02
Oh true I didn't see the GitHub repo
I'll take a look soon and let you know

**Comment by jadjoubran** [comment] 2018-11-16 21:17
`git checkout 89bf8314fee14a8f994915d26db3a80b6df0589a .`
is the `.` (dot) at the end intentional?
I've tried with it, ended up with a state that has a `webpack.config.js` but running `npm run build` shows that `index.html` is part of the precache manifest
![screen shot 2018-11-16 at 22 13 37](https://user-images.githubusercontent.com/2265232/48647767-4b05ea80-e9ed-11e8-9036-1e35ce27b9b6.png)

and I've tried running:
`git checkout 89bf8314fee14a8f994915d26db3a80b6df0589a` (without the `.`) which brought me to  an older version of the project with no `webpack.config.js`

Can you please double check `step 1` and let me know?
Thanks!

**Comment by jeffposnick** [comment] 2019-02-20 21:27
Given that the steps in https://github.com/GoogleChrome/workbox/issues/1692#issuecomment-439530539 were not able to reproduce the issue, I'm going to close this for now.

If there are a different set of steps that can reproduce the issue, please let us know and I'll reopen.

**Closed by jeffposnick** 2019-02-20 21:27 UTC
Labels: Needs More Info

**Comment by blephy** [comment] 2019-02-22 17:51
Yes this is painfull.

I worked out previously in the same issue and i fixed this problème by different methods : 

1. Inject a HTML balise `<meta name="hash" content="<%= webpack.hash %>" />` (work with webpack `4.29.0`and html-webpack-plugin `3.2.0`).
This will force your template to change every build and workbox.injectManifest to trigger it with correct revision hash change.

```js
// htmlWebpackPlugin options used
{
  template: 'src/index.ejs',
  filename: 'index.html',
  minify: true,
  xhtml: true,
  ...
}
```

This fixed my injectManifest plugin and trigger nicely the index.html update with the service-worker in production.

To make your template with other extension [https://github.com/jantimon/html-webpack-plugin/blob/master/docs/template-option.md](https://github.com/jantimon/html-webpack-plugin/blob/master/docs/template-option.md)

**Comment by claymation296** [comment] 2019-12-12 21:52
Thanks @blephy , I've been searching for days and adding the meta tag to my index.html fixed by problem with workbox v4 serving outdated precached files.

 For anyone else running into this issue, I'm using GenerateSW with webpack v4 and workbox 4.3.1.

**Comment by govizlora** [comment] 2021-01-07 07:30
I have the same issue with `html-webpack-plugin`. There is a naiver solution using the [additionalManifestEntries](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.GenerateSW#GenerateSW) parameter. Though, I don't know how to generate the hash, so I used the current time for the revision.

**Comment by blephy** [comment] 2021-04-28 00:09
Yep, you can use this https://github.com/GoogleChrome/workbox/issues/2299#issuecomment-826918658

**Comment by gavinbarron** [comment] 2021-11-10 01:27
@blephy thank you, that was the missing link for me. I had to adjust for webpack5, but you got me close enough I could connect the dots from there.

For anyone visiting this using webpack5 and htmlWebpackPlugin 5.x the setup is a little different to access the hash in your template now as the options have changed a fair bit and you need to inject the hash using [customized templateParameters](https://github.com/jantimon/html-webpack-plugin#options):

```webpack.config
new HtmlWebpackPlugin({
    template: `${sourcePath}/index.html`,
    filename: 'index.html',
    title: siteTitle,
    templateParameters: (
        compilation,
        assets,
        assetTags,
        options
    ) => {
        return {
            compilation,
            webpackConfig: compilation.options,
            htmlWebpackPlugin: {
                tags: assetTags,
                files: assets,
                options,
            },
            hash: compilation.getStats().hash,
        };
    },
    inject: true,
    hash: true,
    minimize: true,
}
```

```meta tag
    <meta name="hash" content="<%= hash %>" />
```
